### ISSUE TITLE
import google `dns` resource is always unsuccess. (2019/5/5)

### ISSUE THREAD

**Issue by sogaoh** [GoogleCloudPlatform/terraformer#10]
I tried to get google `dns` resource, but failed.
The console output is like below:

```
cd /path/to/working_directory 

❯ ./terraformer import google --resources=dns --connect=true --projects=MY_PROJECT, --state=bucket
2019/05/05 13:35:52 google importing project MY_PROJECT
2019/05/05 13:35:52 google importing... dns
2019/05/05 13:35:55 project: required field is not set
2019/05/05 13:35:55 project: required field is not set
2019/05/05 13:35:55 project: required field is not set
2019/05/05 13:35:55 project: required field is not set
2019/05/05 13:35:55 project: required field is not set
2019/05/05 13:35:55 project: required field is not set
2019/05/05 13:35:55 project: required field is not set
2019/05/05 13:35:55 project: required field is not set
2019/05/05 13:35:55 project: required field is not set
2019/05/05 13:35:55 project: required field is not set
panic: interface conversion: interface {} is nil, not string

goroutine 1 [running]:
github.com/GoogleCloudPlatform/terraformer/gcp_terraforming.(*CloudDNSGenerator).PostConvertHook(0xc000168400, 0x2ff0980, 0xc000168400)
	/path/to/working_directory/gcp_terraforming/clouddns.go:125 +0x6a7
github.com/GoogleCloudPlatform/terraformer/cmd.Import(0x2ff0b60, 0xc0000b9e40, 0xc0004ae650, 0x1, 0x1, 0xc0000c6a50, 0x30, 0x2c20d86, 0x9, 0x7ffeefbff8c2, ...)
	/path/to/working_directory/cmd/import.go:88 +0x1ad
github.com/GoogleCloudPlatform/terraformer/cmd.newCmdGoogleImporter.func1(0xc0004c0780, 0xc000331a90, 0x0, 0x5, 0x0, 0x0)
	/path/to/working_directory/cmd/google.go:37 +0x34a
github.com/spf13/cobra.(*Command).execute(0xc0004c0780, 0xc000331a40, 0x5, 0x5, 0xc0004c0780, 0xc000331a40)
	/Users/ME/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:762 +0x465
github.com/spf13/cobra.(*Command).ExecuteC(0xc0004c0280, 0xc0000b9440, 0xc0000b9400, 0xc00047bf88)
	/Users/ME/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:852 +0x2ec
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/ME/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:800
github.com/GoogleCloudPlatform/terraformer/cmd.Execute(0x0, 0x0)
	/path/to/working_directory/cmd/root.go:34 +0x28
main.main()
	/path/to/working_directory/main.go:25 +0x22
```

I've upgraded terraform provider google 1.20 -> 2.0, but `import google dns` has failed as same.

**Comment by PaulKlumpp** [comment]
This one is fixed in the source since 11th of June 2019: https://github.com/GoogleCloudPlatform/terraformer/commit/ee5a188a8068bec5e6490564c08df0e5570aa7a4
