### ISSUE TITLE
panic: interface conversion: interface {} is nil, not []interface {}

### ISSUE THREAD

**Issue by np-ally** [GoogleCloudPlatform/terraformer#1055]
I got this issue, "panic: interface conversion: interface {} is nil, not []interface {}",  while running:
 ```terraformer plan aws --filter=vpc={my-vpcid} --regions=us-east-2 --resources="*"```

Here is the stack trace:

goroutine 1 [running]:
github.com/GoogleCloudPlatform/terraformer/providers/aws.(*Ec2Generator).PostConvertHook(0x14000c0a360, 0x10191c1ec, 0x14000c0a360)
	github.com/GoogleCloudPlatform/terraformer/providers/aws/ec2.go:99 +0x36c
github.com/GoogleCloudPlatform/terraformer/providers/aws.(*AwsFacade).PostConvertHook(0x14000995260, 0x10a1ea3d0, 0x14000995260)
	github.com/GoogleCloudPlatform/terraformer/providers/aws/aws_facade.go:75 +0x34
github.com/GoogleCloudPlatform/terraformer/terraformutils.(*ProvidersMapping).CleanupProviders(0x140021ff518)
	github.com/GoogleCloudPlatform/terraformer/terraformutils/providers_mapping.go:175 +0xc4
github.com/GoogleCloudPlatform/terraformer/cmd.Import(0x10a1da638, 0x1400092e7d0, 0x140012d4000, 0x50, 0x80, 0x10f01a878, 0x0, 0x0, 0x10790a0a1, 0x1e, ...)
	github.com/GoogleCloudPlatform/terraformer/cmd/import.go:104 +0x23c
github.com/GoogleCloudPlatform/terraformer/cmd.importRegionResources(0x1400129e140, 0x1, 0x1, 0x10f01a878, 0x0, 0x0, 0x10790a0a1, 0x1e, 0x10787ee24, 0x9, ...)
	github.com/GoogleCloudPlatform/terraformer/cmd/provider_cmd_aws.go:112 +0x180
github.com/GoogleCloudPlatform/terraformer/cmd.newCmdAwsImporter.func1(0x140010f5b80, 0x140011c1500, 0x0, 0x3, 0x0, 0x0)
	github.com/GoogleCloudPlatform/terraformer/cmd/provider_cmd_aws.go:51 +0x250
github.com/spf13/cobra.(*Command).execute(0x140010f5b80, 0x140011c14d0, 0x3, 0x3, 0x140010f5b80, 0x140011c14d0)
	github.com/spf13/cobra@v1.1.1/command.go:850 +0x320
github.com/spf13/cobra.(*Command).ExecuteC(0x14000ec8b00, 0x14000f9c600, 0x14000112050, 0x109ebaa88)
	github.com/spf13/cobra@v1.1.1/command.go:958 +0x258
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.1.1/command.go:895
github.com/GoogleCloudPlatform/terraformer/cmd.Execute(0x109fd7f08, 0x14000f9c6c0)
	github.com/GoogleCloudPlatform/terraformer/cmd/root.go:36 +0x24
main.main()
	github.com/GoogleCloudPlatform/terraformer/main.go:39 +0x50

I was able to resolve this issue by terminating the one EC2 that was in a stopped state. This whas something todo with the RootDeviceVolume associated with the stopped EC2. It would seem terrafomer should handle this condition, but you can work around it either by terminating or excluding that EC2. 

It is unclear to me if this would happen for any EC2 in a stopped state or if there was something specific in my EC2 that caused this problem. I thought it would be useful to share for others.

**Comment by np-ally** [comment]
I looked into this a little more. This was a very old instance. I had stopped the EC2 and deleted the EBS, but left the EC2 in a stopped state. This is likely the problem as terraformer was trying to find the EBS volume and it wasn't there. Looks to be a corner-case.
