### ISSUE TITLE
Go Exceptions on Import [panic: interface conversion: interface {} is map[string]interface {}, not string]

### ISSUE THREAD

**Issue by jaimi-taos-wellhealth** [GoogleCloudPlatform/terraformer#1130]
After successfully negotiating some issues authenticating with aws-vault/sts creds and running a full aws resource import on a much smaller development account, when I run through the same process on one of the real accounts I want to fully Reverse Engineer, terraformer explodes. 

```
terraformer plan aws --resources='*' --regions=us-east-1 --profile=terraformer_import > terraformer-plan.out
terraformer import plan generated/aws/terraformer/plan.json

terraformer import plan generated/aws/terraformer/plan.json
2021/11/04 12:40:26 aws Connecting....
panic: interface conversion: interface {} is map[string]interface {}, not string

goroutine 1 [running]:
github.com/GoogleCloudPlatform/terraformer/terraformutils.walkAndOverride({0xc006b9fc90, 0x10, 0xa4f794c}, {0xc009d3b2f0, 0x0}, {0xc004fd9aa0, 0x2d}, {0x92d20a0, 0xc009dd5770})
	github.com/GoogleCloudPlatform/terraformer/terraformutils/walk.go:102 +0x965
github.com/GoogleCloudPlatform/terraformer/terraformutils.WalkAndOverride({0xa52f24e, 0xc0010ec720}, {0xc009d3b2f0, 0x15}, {0xc004fd9aa0, 0x58}, {0x92d20a0, 0xc009dd5770})
	github.com/GoogleCloudPlatform/terraformer/terraformutils/walk.go:34 +0x8a
github.com/GoogleCloudPlatform/terraformer/terraformutils.mapResource(0xc0039f12f0, {0xa515e3a, 0xc}, {0xc007d8f878, 0x2, 0xc00091d0c0}, {0xc009d2afa0, 0xc009d2aff0, 0x0, {0xc009ce7a40, ...}, ...}, ...)
	github.com/GoogleCloudPlatform/terraformer/terraformutils/connect.go:54 +0x365
github.com/GoogleCloudPlatform/terraformer/terraformutils.ConnectServices(0xc0033c5cc0, 0x1, 0xa508867)
	github.com/GoogleCloudPlatform/terraformer/terraformutils/connect.go:31 +0x393
github.com/GoogleCloudPlatform/terraformer/cmd.ImportFromPlan({0xb573d50, 0xc0033c5cc0}, 0x4)
	github.com/GoogleCloudPlatform/terraformer/cmd/import.go:223 +0x155
github.com/GoogleCloudPlatform/terraformer/cmd.newCmdPlanImporter.func1(0xc001654580, {0xc0010607f0, 0x1, 0x1})
	github.com/GoogleCloudPlatform/terraformer/cmd/plan.go:83 +0x155
github.com/spf13/cobra.(*Command).execute(0xc001654580, {0xc0010607d0, 0x1, 0x1})
	github.com/spf13/cobra@v1.1.1/command.go:850 +0x60e
github.com/spf13/cobra.(*Command).ExecuteC(0xc001654000)
	github.com/spf13/cobra@v1.1.1/command.go:958 +0x3ad
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.1.1/command.go:895
github.com/GoogleCloudPlatform/terraformer/cmd.Execute()
	github.com/GoogleCloudPlatform/terraformer/cmd/root.go:36 +0x1e
main.main()
	github.com/GoogleCloudPlatform/terraformer/main.go:39 +0x35
```

**Comment by devopsrick** [comment]
The issue is in the aws provider and surfaced in a recent update.  https://github.com/hashicorp/terraform-provider-aws/issues/21633

**Comment by jaimi-taos-wellhealth** [comment]
Hrmmm... I tried to use an older provider, but the issue still remains.

terraform {
  required_providers {
    aws = {
      source = "hashicorp/aws"
      version = "~> 3.64.0"
    }
  }
  required_version = ">= 0.13"
}
