### ISSUE TITLE
import using aws provider fails

### ISSUE THREAD

**Issue by smartkiwi** [GoogleCloudPlatform/terraformer#1166]
Command to run
```
TF_LOG_PATH="./log/" TF_LOG=TRACE terraformer import aws -r "*" --profile myprofile --regions us-west-2 -v 2>&1 | tee ./log/import.log
```

version information
```
User-Agent: APN/1.0 HashiCorp/1.0 Terraform/0.12.31 (+https://www.terraform.io) terraform-provider-aws/3.68.0 (+https://registry.terraform.io/providers/hashicorp/aws) aws-sdk-go/1.42.17 (go1.16; darwin; amd64)

% terraformer --version
version v0.8.18
```

Error itself
```
...
2021/12/07 15:18:12 Filtered number of resources for service vpc: 4
2021/12/07 15:18:12 Filtered number of resources for service codebuild: 0
2021/12/07 15:18:12 Filtered number of resources for service ecrpublic: 0
2021/12/07 15:18:12 Filtered number of resources for service emr: 0
2021/12/07 15:18:12 Filtered number of resources for service firehose: 0
2021/12/07 15:18:12 aws Connecting.... 
2021-12-07T15:18:12.773-0700 [DEBUG] plugin.stdio: received EOF, stopping recv loop: err="rpc error: code = Unavailable desc = transport is closing"
2021-12-07T15:18:12.781-0700 [DEBUG] plugin: plugin process exited: path=.terraform/providers/registry.terraform.io/hashicorp/aws/3.68.0/darwin_amd64/terraform-provider-aws_v3.68.0_x5 pid=28863
2021-12-07T15:18:12.781-0700 [DEBUG] plugin: plugin exited
panic: interface conversion: interface {} is map[string]interface {}, not string

goroutine 1 [running]:
github.com/GoogleCloudPlatform/terraformer/terraformutils.walkAndOverride({0xc0028453a0, 0x10, 0xa5d962d}, {0xc002026de0, 0x0}, {0xc001ab0780, 0x2d}, {0x938b300, 0xc0025f3fb0})
	github.com/GoogleCloudPlatform/terraformer/terraformutils/walk.go:102 +0x965
github.com/GoogleCloudPlatform/terraformer/terraformutils.WalkAndOverride({0xa611283, 0xc002aa14d0}, {0xc002026de0, 0x15}, {0xc001ab0780, 0x58}, {0x938b300, 0xc0025f3fb0})
	github.com/GoogleCloudPlatform/terraformer/terraformutils/walk.go:34 +0x8a
github.com/GoogleCloudPlatform/terraformer/terraformutils.mapResource(0xc002aa1800, {0xa5f7bae, 0xc}, {0xc0025b6f78, 0x2, 0xc000c97fc0}, {0xc0018cf220, 0xc00092b360, 0x0, {0xc0018f8b80, ...}, ...}, ...)
	github.com/GoogleCloudPlatform/terraformer/terraformutils/connect.go:54 +0x365
github.com/GoogleCloudPlatform/terraformer/terraformutils.ConnectServices(0xc00089a9b0, 0x1, 0xa5ea55c)
	github.com/GoogleCloudPlatform/terraformer/terraformutils/connect.go:31 +0x393
github.com/GoogleCloudPlatform/terraformer/cmd.ImportFromPlan({0xb669e30, 0xc00089a9b0}, 0xa5defa0)
	github.com/GoogleCloudPlatform/terraformer/cmd/import.go:223 +0x155
github.com/GoogleCloudPlatform/terraformer/cmd.importFromPlan(_, {{0xc0012db800, 0x51, 0x80}, {0x118c0390, 0x0, 0x0}, {0xa67bf3d, 0x1e}, {0xa5e9032, ...}, ...}, ...)
	github.com/GoogleCloudPlatform/terraformer/cmd/import.go:191 +0x3b3
github.com/GoogleCloudPlatform/terraformer/cmd.Import({_, _}, {{0xc0012db800, 0x51, 0x80}, {0x118c0390, 0x0, 0x0}, {0xa67bf3d, 0x1e}, ...}, ...)
	github.com/GoogleCloudPlatform/terraformer/cmd/import.go:106 +0x319
github.com/GoogleCloudPlatform/terraformer/cmd.importRegionResources({{0xc0014479d0, 0x1, 0x1}, {0x118c0390, 0x0, 0x0}, {0xa67bf3d, 0x1e}, {0xa5e9032, 0x9}, ...}, ...)
	github.com/GoogleCloudPlatform/terraformer/cmd/provider_cmd_aws.go:112 +0x278
github.com/GoogleCloudPlatform/terraformer/cmd.newCmdAwsImporter.func1(0xc0019ff600, {0xa5dbaae, 0x7, 0x7})
	github.com/GoogleCloudPlatform/terraformer/cmd/provider_cmd_aws.go:51 +0x36e
github.com/spf13/cobra.(*Command).execute(0xc0019ff600, {0xc0004de230, 0x7, 0x7})
	github.com/spf13/cobra@v1.1.1/command.go:850 +0x60e
github.com/spf13/cobra.(*Command).ExecuteC(0xc0019fe840)
	github.com/spf13/cobra@v1.1.1/command.go:958 +0x3ad
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.1.1/command.go:895
github.com/GoogleCloudPlatform/terraformer/cmd.Execute()
	github.com/GoogleCloudPlatform/terraformer/cmd/root.go:36 +0x1e
main.main()
	github.com/GoogleCloudPlatform/terraformer/main.go:39 +0x35

```

Note that if I run one command per resource - import works without this panic error.

**Comment by tomahawk-pilot** [comment]
same issue for me.

**Comment by tomahawk-pilot** [comment]
panic: interface conversion: interface {} is map[string]interface {}, not string
