### ISSUE TITLE
AWS Import error

### ISSUE THREAD

**Issue by Lutacon** [GoogleCloudPlatform/terraformer#1223]
It happens on a clean installation. I'm unable to import any resource.

```terraformer import aws --resources=es -v --profile=macnificos```
```
2022/02/04 11:28:01 aws importing default region
2022-02-04T11:28:01.587+0100 [INFO]  plugin: configuring client automatic mTLS
2022-02-04T11:28:01.603+0100 [DEBUG] plugin: starting plugin: path=/Users/luistacon/.terraform.d/plugins/darwin_arm64/terraform-provider-aws_v3.74.0_x5 args=["/Users/luistacon/.terraform.d/plugins/darwin_arm64/terraform-provider-aws_v3.74.0_x5"]
2022-02-04T11:28:01.605+0100 [DEBUG] plugin: plugin started: path=/Users/luistacon/.terraform.d/plugins/darwin_arm64/terraform-provider-aws_v3.74.0_x5 pid=50126
2022-02-04T11:28:01.605+0100 [DEBUG] plugin: waiting for RPC address: path=/Users/luistacon/.terraform.d/plugins/darwin_arm64/terraform-provider-aws_v3.74.0_x5
2022-02-04T11:28:02.224+0100 [INFO]  plugin.terraform-provider-aws_v3.74.0_x5: configuring server automatic mTLS: timestamp=2022-02-04T11:28:02.223+0100
2022-02-04T11:28:02.252+0100 [DEBUG] plugin.terraform-provider-aws_v3.74.0_x5: plugin address: address=/var/folders/gk/tqq98ld97r33m5d4lrkr4l_h0000gn/T/plugin798400517 network=unix timestamp=2022-02-04T11:28:02.252+0100
2022-02-04T11:28:02.252+0100 [DEBUG] plugin: using plugin: version=5
2022-02-04T11:28:02.273+0100 [TRACE] plugin.stdio: waiting for stdio data
2022-02-04T11:28:02.274+0100 [TRACE] plugin.terraform-provider-aws_v3.74.0_x5: Received request: @caller=/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.5.0/tfprotov5/tf5server/server.go:329 tf_proto_version=5 tf_req_id=efd3f2ef-dae5-a9a1-c137-821d1d3e292f tf_rpc=GetSchema @module=sdk.proto tf_provider_addr=provider timestamp=2022-02-04T11:28:02.274+0100
2022-02-04T11:28:02.274+0100 [TRACE] plugin.terraform-provider-aws_v3.74.0_x5: Calling downstream: tf_provider_addr=provider tf_rpc=GetSchema @module=sdk.proto tf_proto_version=5 tf_req_id=efd3f2ef-dae5-a9a1-c137-821d1d3e292f @caller=/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.5.0/tfprotov5/tf5server/server.go:336 timestamp=2022-02-04T11:28:02.274+0100
2022-02-04T11:28:02.292+0100 [TRACE] plugin.terraform-provider-aws_v3.74.0_x5: Called downstream: tf_req_id=efd3f2ef-dae5-a9a1-c137-821d1d3e292f @caller=/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.5.0/tfprotov5/tf5server/server.go:342 @module=sdk.proto tf_proto_version=5 tf_provider_addr=provider tf_rpc=GetSchema timestamp=2022-02-04T11:28:02.292+0100
2022-02-04T11:28:02.298+0100 [TRACE] plugin.terraform-provider-aws_v3.74.0_x5: Served request: tf_provider_addr=provider tf_req_id=efd3f2ef-dae5-a9a1-c137-821d1d3e292f tf_rpc=GetSchema tf_proto_version=5 @caller=/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.5.0/tfprotov5/tf5server/server.go:348 @module=sdk.proto timestamp=2022-02-04T11:28:02.298+0100
2022-02-04T11:28:02.347+0100 [TRACE] plugin.terraform-provider-aws_v3.74.0_x5: Received request: @caller=/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.5.0/tfprotov5/tf5server/server.go:379 @module=sdk.proto tf_provider_addr=provider tf_req_id=0d947388-9d5d-fe1d-b2e9-675fefc7dfc8 tf_proto_version=5 tf_rpc=Configure timestamp=2022-02-04T11:28:02.347+0100
2022-02-04T11:28:02.347+0100 [TRACE] plugin.terraform-provider-aws_v3.74.0_x5: Calling downstream: tf_req_id=0d947388-9d5d-fe1d-b2e9-675fefc7dfc8 @module=sdk.proto tf_proto_version=5 tf_provider_addr=provider tf_rpc=Configure @caller=/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.5.0/tfprotov5/tf5server/server.go:386 timestamp=2022-02-04T11:28:02.347+0100
2022-02-04T11:28:02.350+0100 [INFO]  plugin.terraform-provider-aws_v3.74.0_x5: 2022/02/04 11:28:02 [INFO] Attempting to use session-derived credentials: timestamp=2022-02-04T11:28:02.350+0100
2022-02-04T11:28:02.350+0100 [TRACE] plugin.terraform-provider-aws_v3.74.0_x5: Called downstream: tf_rpc=Configure @caller=/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.5.0/tfprotov5/tf5server/server.go:392 tf_proto_version=5 tf_provider_addr=provider tf_req_id=0d947388-9d5d-fe1d-b2e9-675fefc7dfc8 @module=sdk.proto timestamp=2022-02-04T11:28:02.350+0100
2022-02-04T11:28:02.350+0100 [TRACE] plugin.terraform-provider-aws_v3.74.0_x5: Served request: tf_proto_version=5 tf_req_id=0d947388-9d5d-fe1d-b2e9-675fefc7dfc8 tf_rpc=Configure @caller=/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.5.0/tfprotov5/tf5server/server.go:398 tf_provider_addr=provider @module=sdk.proto timestamp=2022-02-04T11:28:02.350+0100
2022/02/04 11:28:02 aws importing... es
Assume Role MFA token code: 813585
2022/02/04 11:28:08 aws done importing es
2022/02/04 11:28:08 Number of resources for service es: 1
2022/02/04 11:28:08 Refreshing state... aws_elasticsearch_domain.tfer--monitoring-development
2022-02-04T11:28:08.390+0100 [TRACE] plugin.terraform-provider-aws_v3.74.0_x5: Received request: @caller=/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.5.0/tfprotov5/tf5server/server.go:545 tf_resource_type=aws_elasticsearch_domain @module=sdk.proto tf_proto_version=5 tf_provider_addr=provider tf_req_id=c76a4a60-93f1-cb0c-949f-1c7e18b3421e tf_rpc=ReadResource timestamp=2022-02-04T11:28:08.390+0100
2022-02-04T11:28:08.390+0100 [TRACE] plugin.terraform-provider-aws_v3.74.0_x5: Calling downstream: tf_proto_version=5 tf_req_id=c76a4a60-93f1-cb0c-949f-1c7e18b3421e @module=sdk.proto tf_provider_addr=provider tf_resource_type=aws_elasticsearch_domain tf_rpc=ReadResource @caller=/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.5.0/tfprotov5/tf5server/server.go:552 timestamp=2022-02-04T11:28:08.390+0100
2022-02-04T11:28:08.395+0100 [TRACE] plugin.terraform-provider-aws_v3.74.0_x5: Served request: tf_provider_addr=provider tf_req_id=c76a4a60-93f1-cb0c-949f-1c7e18b3421e tf_rpc=ReadResource @caller=/opt/goenv/versions/1.16.0/src/runtime/panic.go:965 @module=sdk.proto tf_proto_version=5 tf_resource_type=aws_elasticsearch_domain timestamp=2022-02-04T11:28:08.395+0100
2022-02-04T11:28:08.398+0100 [DEBUG] plugin.terraform-provider-aws_v3.74.0_x5: panic: interface conversion: interface {} is nil, not *conns.AWSClient
2022-02-04T11:28:08.398+0100 [DEBUG] plugin.terraform-provider-aws_v3.74.0_x5:
2022-02-04T11:28:08.398+0100 [DEBUG] plugin.terraform-provider-aws_v3.74.0_x5: goroutine 22 [running]:
2022-02-04T11:28:08.399+0100 [DEBUG] plugin.terraform-provider-aws_v3.74.0_x5: github.com/hashicorp/terraform-provider-aws/internal/service/elasticsearch.resourceDomainRead(0x140024ace00, 0x0, 0x0, 0x10b0337d0, 0x0)
2022-02-04T11:28:08.399+0100 [DEBUG] plugin.terraform-provider-aws_v3.74.0_x5: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-aws/internal/service/elasticsearch/domain.go:704 +0x20a8
2022-02-04T11:28:08.399+0100 [DEBUG] plugin.terraform-provider-aws_v3.74.0_x5: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0x14000c88700, 0x10b583e98, 0x140024942c0, 0x140024ace00, 0x0, 0x0, 0x0, 0x0, 0x0)
2022-02-04T11:28:08.399+0100 [DEBUG] plugin.terraform-provider-aws_v3.74.0_x5: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/helper/schema/resource.go:346 +0x170
2022-02-04T11:28:08.399+0100 [DEBUG] plugin.terraform-provider-aws_v3.74.0_x5: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0x14000c88700, 0x10b583e98, 0x140024942c0, 0x140024bd450, 0x0, 0x0, 0x0, 0x0, 0x140024ce060, 0x0)
2022-02-04T11:28:08.399+0100 [DEBUG] plugin.terraform-provider-aws_v3.74.0_x5: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/helper/schema/resource.go:635 +0x160
2022-02-04T11:28:08.399+0100 [DEBUG] plugin.terraform-provider-aws_v3.74.0_x5: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0x1400000c948, 0x10b583e98, 0x140024942c0, 0x14002494300, 0x107f1724e, 0x12, 0x0)
2022-02-04T11:28:08.399+0100 [DEBUG] plugin.terraform-provider-aws_v3.74.0_x5: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/helper/schema/grpc_provider.go:576 +0x3ac
2022-02-04T11:28:08.399+0100 [DEBUG] plugin.terraform-provider-aws_v3.74.0_x5: github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ReadResource(0x1400011c680, 0x10b583f40, 0x140024942c0, 0x14002490180, 0x0, 0x0, 0x0)
2022-02-04T11:28:08.399+0100 [DEBUG] plugin.terraform-provider-aws_v3.74.0_x5: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.5.0/tfprotov5/tf5server/server.go:553 +0x254
2022-02-04T11:28:08.399+0100 [DEBUG] plugin.terraform-provider-aws_v3.74.0_x5: github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler(0x10adc9ca0, 0x1400011c680, 0x10b583f40, 0x140014fe1e0, 0x14002490120, 0x0, 0x10b583f40, 0x140014fe1e0, 0x140024a6000, 0x1bd)
2022-02-04T11:28:08.399+0100 [DEBUG] plugin.terraform-provider-aws_v3.74.0_x5: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.5.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:344 +0x1c8
2022-02-04T11:28:08.399+0100 [DEBUG] plugin.terraform-provider-aws_v3.74.0_x5: google.golang.org/grpc.(*Server).processUnaryRPC(0x1400013bc00, 0x10b5b0dd8, 0x14000424600, 0x1400249e000, 0x140017589f0, 0x11007db30, 0x0, 0x0, 0x0)
2022-02-04T11:28:08.399+0100 [DEBUG] plugin.terraform-provider-aws_v3.74.0_x5: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:1194 +0x3e8
2022-02-04T11:28:08.399+0100 [DEBUG] plugin.terraform-provider-aws_v3.74.0_x5: google.golang.org/grpc.(*Server).handleStream(0x1400013bc00, 0x10b5b0dd8, 0x14000424600, 0x1400249e000, 0x0)
2022-02-04T11:28:08.399+0100 [DEBUG] plugin.terraform-provider-aws_v3.74.0_x5: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:1517 +0xa50
2022-02-04T11:28:08.399+0100 [DEBUG] plugin.terraform-provider-aws_v3.74.0_x5: google.golang.org/grpc.(*Server).serveStreams.func1.2(0x14000362c90, 0x1400013bc00, 0x10b5b0dd8, 0x14000424600, 0x1400249e000)
2022-02-04T11:28:08.399+0100 [DEBUG] plugin.terraform-provider-aws_v3.74.0_x5: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:859 +0x94
2022-02-04T11:28:08.399+0100 [DEBUG] plugin.terraform-provider-aws_v3.74.0_x5: created by google.golang.org/grpc.(*Server).serveStreams.func1
2022-02-04T11:28:08.399+0100 [DEBUG] plugin.terraform-provider-aws_v3.74.0_x5: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:857 +0x1f8
2022-02-04T11:28:08.406+0100 [DEBUG] plugin: plugin process exited: path=/Users/luistacon/.terraform.d/plugins/darwin_arm64/terraform-provider-aws_v3.74.0_x5 pid=50126 error="exit status 2"
2022-02-04T11:28:08.406+0100 [DEBUG] plugin.stdio: received EOF, stopping recv loop: err="rpc error: code = Unavailable desc = transport is closing"
2022/02/04 11:28:08 rpc error: code = Unavailable desc = transport is closing
2022/02/04 11:28:08 WARN: Fail read resource from provider, wait 300ms before retry
2022/02/04 11:28:08 rpc error: code = Canceled desc = context canceled
2022/02/04 11:28:08 WARN: Fail read resource from provider, wait 300ms before retry
2022/02/04 11:28:09 rpc error: code = Canceled desc = context canceled
2022/02/04 11:28:09 WARN: Fail read resource from provider, wait 300ms before retry
2022/02/04 11:28:09 rpc error: code = Canceled desc = context canceled
2022/02/04 11:28:09 WARN: Fail read resource from provider, wait 300ms before retry
2022/02/04 11:28:09 rpc error: code = Canceled desc = context canceled
2022/02/04 11:28:09 WARN: Fail read resource from provider, wait 300ms before retry
2022/02/04 11:28:09 Fail read resource from provider, trying import command
2022/02/04 11:28:09 rpc error: code = Canceled desc = context canceled
2022/02/04 11:28:09 ERROR: Unable to refresh resource tfer--monitoring-development
2022/02/04 11:28:09 Filtered number of resources for service es: 0
2022/02/04 11:28:09 aws Connecting....
2022/02/04 11:28:09 aws save es
2022/02/04 11:28:09 aws save tfstate for es
2022-02-04T11:28:09.918+0100 [DEBUG] plugin: plugin exited```

**Comment by Lutacon** [comment]
```
❯ terraformer --version
version v0.8.18

❯ go version
go version go1.17.6 darwin/arm64

**Comment by Lutacon** [comment]
Well it works with another user that doesn't have 2FA.

User not working:
```
cat ~/.aws/config
[profile macnificos]
source_profile = macnificos-luis
role_arn = arn:aws:iam::XXX:role/terraform
mfa_serial = arn:aws:iam::XXXXX:mfa/luis
region = eu-west-1
output = json
❯ cat ~/.aws/credentials
[macnificos-luis]
aws_access_key_id = X
aws_secret_access_key = X

```

User working

```
cat ~/.aws/config
[profile itmacnificos]
region = eu-west-1
output = json
❯ cat ~/.aws/credentials
[itmacnificos]
aws_access_key_id = X
aws_secret_access_key = X

**Comment by dvmrry** [comment]
@Lutacon - did you ever find any way around this limitation short of using an account with no MFA serial?

**Comment by Lutacon** [comment]
@dvmrry nope. The only solution i found it was using an account without no MFA

**Comment by ralexander-phi** [comment]
Most AWS creds with high privileges I've worked with have required MFA, this seems important to me. (ping to remove the stale label).
