### ISSUE TITLE
Segmentation fault when importing AWS security group

### ISSUE THREAD

**Issue by esmail** [GoogleCloudPlatform/terraformer#1479]
```
./terraformer-all-darwin-amd64 import aws --resources=sg
2022/09/23 17:37:23 aws importing default region
2022/09/23 17:37:25 aws importing... sg
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x66d1d3f]

goroutine 1 [running]:
github.com/GoogleCloudPlatform/terraformer/providers/aws.fromPort(...)
	/home/runner/work/terraformer/terraformer/providers/aws/sg.go:362
github.com/GoogleCloudPlatform/terraformer/providers/aws.baseRuleAttributes({_, _}, {0x0, 0xc001ace480, {0x121e7128, 0x0, 0x0}, {0x121e7128, 0x0, 0x0}, ...}, ...)
	/home/runner/work/terraformer/terraformer/providers/aws/sg.go:164 +0x33f
github.com/GoogleCloudPlatform/terraformer/providers/aws.processRule({0x0, 0xc001ace480, {0x121e7128, 0x0, 0x0}, {0x121e7128, 0x0, 0x0}, {0x121e7128, 0x0, ...}, ...}, ...)
	/home/runner/work/terraformer/terraformer/providers/aws/sg.go:126 +0xa98
github.com/GoogleCloudPlatform/terraformer/providers/aws.SecurityGenerator.createResources({{{{0xc000a0abe0, 0x2}, {0x0, 0x0, 0x0}, {0xaf01276, 0x3}, 0xc003308720, {0x121e7128, 0x0, ...}, ...}}}, ...)
	/home/runner/work/terraformer/terraformer/providers/aws/sg.go:81 +0x6ed
github.com/GoogleCloudPlatform/terraformer/providers/aws.(*SecurityGenerator).InitResources(0xc0000af9e0)
	/home/runner/work/terraformer/terraformer/providers/aws/sg.go:260 +0x3b0
github.com/GoogleCloudPlatform/terraformer/providers/aws.(*AwsFacade).InitResources(0xc00022c8c0?)
	/home/runner/work/terraformer/terraformer/providers/aws/aws_facade.go:61 +0x26
github.com/GoogleCloudPlatform/terraformer/cmd.initServiceResources({_, _}, {_, _}, {{0xc0005a7e80, 0x1, 0x1}, {0x121e7128, 0x0, 0x0}, ...}, ...)
	/home/runner/work/terraformer/terraformer/cmd/import.go:209 +0x21e
github.com/GoogleCloudPlatform/terraformer/cmd.initAllServicesResources(_, {{0xc0005a7e80, 0x1, 0x1}, {0x121e7128, 0x0, 0x0}, {0xafad8a7, 0x1e}, {0xaf10118, ...}, ...}, ...)
	/home/runner/work/terraformer/terraformer/cmd/import.go:166 +0x1a7
github.com/GoogleCloudPlatform/terraformer/cmd.Import({_, _}, {{0xc0005a7e80, 0x1, 0x1}, {0x121e7128, 0x0, 0x0}, {0xafad8a7, 0x1e}, ...}, ...)
	/home/runner/work/terraformer/terraformer/cmd/import.go:98 +0x2a5
github.com/GoogleCloudPlatform/terraformer/cmd.importRegionResources({{0xc0005a7e50, 0x1, 0x1}, {0x121e7128, 0x0, 0x0}, {0xafad8a7, 0x1e}, {0xaf10118, 0x9}, ...}, ...)
	/home/runner/work/terraformer/terraformer/cmd/provider_cmd_aws.go:121 +0x292
github.com/GoogleCloudPlatform/terraformer/cmd.newCmdAwsImporter.func1(0xc0013f4580?, {0xaf0239e?, 0x1?, 0x1?})
	/home/runner/work/terraformer/terraformer/cmd/provider_cmd_aws.go:66 +0x13e
github.com/spf13/cobra.(*Command).execute(0xc0013f4580, {0xc0005a7e30, 0x1, 0x1})
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:850 +0x67c
github.com/spf13/cobra.(*Command).ExecuteC(0xc0013a5340)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:958 +0x39d
github.com/spf13/cobra.(*Command).Execute(...)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:895
github.com/GoogleCloudPlatform/terraformer/cmd.Execute()
	/home/runner/work/terraformer/terraformer/cmd/root.go:36 +0x1e
main.main()
	/home/runner/work/terraformer/terraformer/main.go:39 +0x50
```

**Comment by maresb** [comment]
I just hit this on v0.8.22, but it seems to be resolved in `main`.
