### ISSUE TITLE
unknown resource type google_compute_region_instance_group

### ISSUE THREAD

**Issue by andrasnemethcg** [GoogleCloudPlatform/terraformer#1509]
Running `terraformer plan google --projects PROJECT --resources="*" -z ZONE --compact` gives unkown type error:
```
terraform -v
Terraform v1.3.2
on linux_amd64
+ provider registry.terraform.io/hashicorp/google v4.23.0
terraformer -v
version v0.8.22
```
```
panic: unknown resource type google_compute_region_instance_group

goroutine 1742 [running]:
github.com/hashicorp/terraform/plugin.(*GRPCProvider).getResourceSchema(0x12906e0?, {0x129449e, 0x24})
        /home/runner/go/pkg/mod/github.com/hashicorp/terraform@v0.12.31/plugin/grpc_provider.go:92 +0x10b
github.com/hashicorp/terraform/plugin.(*GRPCProvider).ReadResource(0xc0001a8d90, {{0x129449e, 0x24}, {{{0x14c65d8, 0xc0025f78c0}}, {0x1077320, 0xc00268cff0}}, {0x1d085f8, 0x0, 0x0}})
        /home/runner/go/pkg/mod/github.com/hashicorp/terraform@v0.12.31/plugin/grpc_provider.go:321 +0x74
github.com/GoogleCloudPlatform/terraformer/terraformutils/providerwrapper.(*ProviderWrapper).Refresh(0xc0000d12d0, 0xc0011a3f40, 0xc0011a3ea0)
        /home/runner/work/terraformer/terraformer/terraformutils/providerwrapper/provider.go:171 +0x3a9
github.com/GoogleCloudPlatform/terraformer/terraformutils.(*Resource).Refresh(0xc001a7a990, 0x37?)
        /home/runner/work/terraformer/terraformer/terraformutils/resource.go:130 +0x4e
github.com/GoogleCloudPlatform/terraformer/terraformutils.RefreshResourceWorker(0xc001cd6fd0?, 0x88bcc6?, 0xc0007a7500?)
        /home/runner/work/terraformer/terraformer/terraformutils/utils.go:153 +0xad
created by github.com/GoogleCloudPlatform/terraformer/terraformutils.RefreshResources
        /home/runner/work/terraformer/terraformer/terraformutils/utils.go:80 +0xe7
```

**Comment by andrasnemethcg** [comment]
Up
