### ISSUE TITLE
Failing on Vault Import - pki secrets backend

### ISSUE THREAD

**Issue by evilmog** [GoogleCloudPlatform/terraformer#1571]
My Apologies for the lack of proper code blocks, I'm having issues with the markdown. Running terraform 1.3.5 and 1.3.3, vault version 1.12.1 with latest terraformer from brew on macos.

2022/11/24 12:37:28 Refreshing state... vault_mount.tfer--rpt-pki-root
panic: unknown resource type vault_pki_secret_backend

goroutine 580 [running]:
github.com/hashicorp/terraform/plugin.(*GRPCProvider).getResourceSchema(0xe111a5d?, {0xc001dd8c78, 0x18})
	github.com/hashicorp/terraform@v0.12.31/plugin/grpc_provider.go:92 +0x10b
github.com/hashicorp/terraform/plugin.(*GRPCProvider).ReadResource(0xc000a0e8c0, {{0xc001dd8c78, 0x18}, {{{0xf0b0bd8, 0xc000658340}}, {0xcb81b00, 0xc0017d6c00}}, {0x152ef6d8, 0x0, 0x0}})
	github.com/hashicorp/terraform@v0.12.31/plugin/grpc_provider.go:321 +0x74
github.com/GoogleCloudPlatform/terraformer/terraformutils/providerwrapper.(*ProviderWrapper).Refresh(0xc00016a9a0, 0xc001d87450, 0xc001d87400)
	github.com/GoogleCloudPlatform/terraformer/terraformutils/providerwrapper/provider.go:171 +0x3a9
github.com/GoogleCloudPlatform/terraformer/terraformutils.(*Resource).Refresh(0xc001f886c0, 0x27?)
	github.com/GoogleCloudPlatform/terraformer/terraformutils/resource.go:130 +0x4e
github.com/GoogleCloudPlatform/terraformer/terraformutils.RefreshResourceWorker(0x4498d0a?, 0x2e?, 0x0?)
	github.com/GoogleCloudPlatform/terraformer/terraformutils/utils.go:153 +0xad
created by github.com/GoogleCloudPlatform/terraformer/terraformutils.RefreshResources
	github.com/GoogleCloudPlatform/terraformer/terraformutils/utils.go:80 +0xe7

	
`terraform {
  required_providers {
    vault = {
      source = "hashicorp/vault"
      version = "3.11.0"
    }
  }
}`

**Comment by evilmog** [comment]
It seems to die on the vault_pki_secret backend

2022/11/24 12:37:28 Refreshing state... vault_jwt_auth_backend_role.tfer--jwt_pentest
2022/11/24 12:37:28 Refreshing state... vault_policy.tfer--ansible
2022/11/24 12:37:28 Refreshing state... vault_mount.tfer--pki_root
2022/11/24 12:37:28 Refreshing state... vault_mount.tfer--tester_pki
2022/11/24 12:37:28 Refreshing state... vault_ssh_secret_backend_role.tfer--ssh-client-signer_ssh-oidc
2022/11/24 12:37:28 Refreshing state... vault_pki_secret_backend.tfer--pki_root
2022/11/24 12:37:28 Refreshing state... vault_mount.tfer--rpt-pki-root
panic: unknown resource type vault_pki_secret_backend
