### ISSUE TITLE
Error: Import AWS security_groups "panic: runtime error: invalid memory address or nil pointer dereference"

### ISSUE THREAD

**Issue by vunhan** [GoogleCloudPlatform/terraformer#1601]
I got a 'nil pointer dereference' while importing AWS security_groups

`terraformer import aws --resources=sg --connect=true`

```2023/01/10 11:45:36 aws importing default region
2023/01/10 11:45:40 aws importing... sg
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x106faea74]

goroutine 1 [running]:
github.com/GoogleCloudPlatform/terraformer/providers/aws.fromPort(...)
	github.com/GoogleCloudPlatform/terraformer/providers/aws/sg.go:362
github.com/GoogleCloudPlatform/terraformer/providers/aws.baseRuleAttributes({0x1097aed86, 0x6}, {0x0, 0x140016ce290, {0x140012f9dd0, 0x1, 0x1}, {0x112a328d8, 0x0, 0x0}, ...}, ...)
	github.com/GoogleCloudPlatform/terraformer/providers/aws/sg.go:164 +0x324
github.com/GoogleCloudPlatform/terraformer/providers/aws.processRule({0x0, 0x140016ce290, {0x140012f9dd0, 0x1, 0x1}, {0x112a328d8, 0x0, 0x0}, {0x112a328d8, 0x0, ...}, ...}, ...)
	github.com/GoogleCloudPlatform/terraformer/providers/aws/sg.go:145 +0x538
github.com/GoogleCloudPlatform/terraformer/providers/aws.SecurityGenerator.createResources({{{{0x10ae4a120, 0x140013c8cc0}, {0x5a, 0x14001342000, 0x0}, {0x0, 0x0}, 0x0, {0x0, 0x0, ...}, ...}}}, ...)
	github.com/GoogleCloudPlatform/terraformer/providers/aws/sg.go:84 +0x618
github.com/GoogleCloudPlatform/terraformer/providers/aws.(*SecurityGenerator).InitResources(0x14000d479e0)
	github.com/GoogleCloudPlatform/terraformer/providers/aws/sg.go:260 +0x2b8
github.com/GoogleCloudPlatform/terraformer/providers/aws.(*AwsFacade).InitResources(0x140000b3db0?)
	github.com/GoogleCloudPlatform/terraformer/providers/aws/aws_facade.go:61 +0x28
github.com/GoogleCloudPlatform/terraformer/cmd.initServiceResources({_, _}, {_, _}, {{0x140007239b0, 0x1, 0x1}, {0x112a328d8, 0x0, 0x0}, ...}, ...)
	github.com/GoogleCloudPlatform/terraformer/cmd/import.go:209 +0x1a4
github.com/GoogleCloudPlatform/terraformer/cmd.initAllServicesResources(_, {{0x140007239b0, 0x1, 0x1}, {0x112a328d8, 0x0, 0x0}, {0x109856d51, 0x1e}, {0x1097b929e, ...}, ...}, ...)
	github.com/GoogleCloudPlatform/terraformer/cmd/import.go:166 +0x12c
github.com/GoogleCloudPlatform/terraformer/cmd.Import({_, _}, {{0x140007239b0, 0x1, 0x1}, {0x112a328d8, 0x0, 0x0}, {0x109856d51, 0x1e}, ...}, ...)
	github.com/GoogleCloudPlatform/terraformer/cmd/import.go:98 +0x17c
github.com/GoogleCloudPlatform/terraformer/cmd.importRegionResources({{0x14000723980, 0x1, 0x1}, {0x112a328d8, 0x0, 0x0}, {0x109856d51, 0x1e}, {0x1097b929e, 0x9}, ...}, ...)
	github.com/GoogleCloudPlatform/terraformer/cmd/provider_cmd_aws.go:121 +0x1f8
github.com/GoogleCloudPlatform/terraformer/cmd.newCmdAwsImporter.func1(0x1400127c000?, {0x1097ab405?, 0x2?, 0x2?})
	github.com/GoogleCloudPlatform/terraformer/cmd/provider_cmd_aws.go:66 +0xe0
github.com/spf13/cobra.(*Command).execute(0x1400127c000, {0x1400030f320, 0x2, 0x2})
	github.com/spf13/cobra@v1.1.1/command.go:850 +0x4c4
github.com/spf13/cobra.(*Command).ExecuteC(0x14001224dc0)
	github.com/spf13/cobra@v1.1.1/command.go:958 +0x34c
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.1.1/command.go:895
github.com/GoogleCloudPlatform/terraformer/cmd.Execute()
	github.com/GoogleCloudPlatform/terraformer/cmd/root.go:36 +0x20
main.main()
	github.com/GoogleCloudPlatform/terraformer/main.go:39 +0x54
```

**Comment by akaillidan** [comment]
I think the problem is the spaces in the names of the groups

**Comment by jsermer** [comment]
i believe it's been fixed already via this merged PR: https://github.com/GoogleCloudPlatform/terraformer/pull/1486

since they have not tagged a new version and subsequently no new packages have been generated, you have to build from source.

**Comment by jsermer** [comment]
are there plans to provide an updated build which includes the fix for this isse?

**Comment by jsermer** [comment]
ping

**Comment by shblue21** [comment]
A new version was released in July. Would you like to test it? Are you still getting errors with the new version?
