### ISSUE TITLE
Nil pointer dereference when import AWS Security Group 

### ISSUE THREAD

**Issue by LockedThread** [GoogleCloudPlatform/terraformer#1606]
Operating System: `Ubuntu 20.04`

Command:
```
terraformer import aws --resources="*" --exclude="sg" --regions us-east-2
```

```2023/01/15 17:53:09 aws importing... sg
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x5ae1cdf]

goroutine 1 [running]:
github.com/GoogleCloudPlatform/terraformer/providers/aws.fromPort(...)
	/home/runner/work/terraformer/terraformer/providers/aws/sg.go:362
github.com/GoogleCloudPlatform/terraformer/providers/aws.baseRuleAttributes({_, _}, {0x0, 0xc001869910, {0xc0033ca210, 0x1, 0x1}, {0x116e9878, 0x0, 0x0}, ...}, ...)
	/home/runner/work/terraformer/terraformer/providers/aws/sg.go:164 +0x33f
github.com/GoogleCloudPlatform/terraformer/providers/aws.processRule({0x0, 0xc001869910, {0xc0033ca210, 0x1, 0x1}, {0x116e9878, 0x0, 0x0}, {0x116e9878, 0x0, ...}, ...}, ...)
	/home/runner/work/terraformer/terraformer/providers/aws/sg.go:145 +0x718
github.com/GoogleCloudPlatform/terraformer/providers/aws.SecurityGenerator.createResources({{{{0xa3ea1ce, 0x2}, {0x0, 0x0, 0x0}, {0xa3eb0b0, 0x3}, 0xc00334f140, {0x116e9878, 0x0, ...}, ...}}}, ...)
	/home/runner/work/terraformer/terraformer/providers/aws/sg.go:84 +0x7cd
github.com/GoogleCloudPlatform/terraformer/providers/aws.(*SecurityGenerator).InitResources(0xc0033a3c20)
	/home/runner/work/terraformer/terraformer/providers/aws/sg.go:260 +0x3b0
github.com/GoogleCloudPlatform/terraformer/providers/aws.(*AwsFacade).InitResources(0xc0030d1630?)
	/home/runner/work/terraformer/terraformer/providers/aws/aws_facade.go:61 +0x26
github.com/GoogleCloudPlatform/terraformer/cmd.initServiceResources({_, _}, {_, _}, {{0xc000f6f800, 0x54, 0x80}, {0x116e9878, 0x0, 0x0}, ...}, ...)
	/home/runner/work/terraformer/terraformer/cmd/import.go:209 +0x21e
github.com/GoogleCloudPlatform/terraformer/cmd.initAllServicesResources(_, {{0xc000f6f800, 0x54, 0x80}, {0x116e9878, 0x0, 0x0}, {0xa497bb9, 0x1e}, {0xa3f9f79, ...}, ...}, ...)
	/home/runner/work/terraformer/terraformer/cmd/import.go:166 +0x1a7
github.com/GoogleCloudPlatform/terraformer/cmd.Import({_, _}, {{0xc000f6f800, 0x54, 0x80}, {0x116e9878, 0x0, 0x0}, {0xa497bb9, 0x1e}, ...}, ...)
	/home/runner/work/terraformer/terraformer/cmd/import.go:98 +0x2a5
github.com/GoogleCloudPlatform/terraformer/cmd.importRegionResources({{0xc000c38b60, 0x1, 0x1}, {0x116e9878, 0x0, 0x0}, {0xa497bb9, 0x1e}, {0xa3f9f79, 0x9}, ...}, ...)
	/home/runner/work/terraformer/terraformer/cmd/provider_cmd_aws.go:121 +0x292
github.com/GoogleCloudPlatform/terraformer/cmd.newCmdAwsImporter.func1(0xc001010000?, {0xa3ec1d8?, 0x3?, 0x3?})
	/home/runner/work/terraformer/terraformer/cmd/provider_cmd_aws.go:58 +0x5ae
github.com/spf13/cobra.(*Command).execute(0xc001010000, {0xc0018f30b0, 0x3, 0x3})
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:850 +0x67c
github.com/spf13/cobra.(*Command).ExecuteC(0xc000afcdc0)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:958 +0x39d
github.com/spf13/cobra.(*Command).Execute(...)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:895
github.com/GoogleCloudPlatform/terraformer/cmd.Execute()
	/home/runner/work/terraformer/terraformer/cmd/root.go:36 +0x1e
main.main()
	/home/runner/work/terraformer/terraformer/main.go:39 +0x50```

**Comment by tyler-dunkel** [comment]
Were you able to find any fix for this?

**Comment by LockedThread** [comment]
> Were you able to find any fix for this?

by not importing security groups :/
not really a fix, more of a bandaid

**Comment by tyler-dunkel** [comment]
we plan to do the same and possibly fork terraformer for a longer term fix

**Comment by LockedThread** [comment]
> we plan to do the same and possibly fork terraformer for a longer term fix

if you make a fix please lmk, I would really appreciate it. I am reverse engineering the company I work for's AWS infrastructure because they the contractor they paid to set it up didn't give them the terraform files.

**Comment by jsermer** [comment]
i believe it's been fixed already via this merged PR:  https://github.com/GoogleCloudPlatform/terraformer/pull/1486

since they have not tagged a new version and subsequently no new packages have been generated, you have to build from source.

**Comment by jsermer** [comment]
are there plans to provide an updated build which includes the fix for this isse?

**Comment by jsermer** [comment]
ping
