### ISSUE TITLE
Terraformer import crashes while importing gcp resourses.

### ISSUE THREAD

**Issue by siba-prosimo** [GoogleCloudPlatform/terraformer#1769]
I am trying to import gcp resources using terraformer import but the plugin crashes while doing so and I do receive a blank state file in the end.
terraform {
	required_providers {
		google = {
	    version = "~> 4.78.0"
		}
  }
}
Crash Report:

2023-08-16T14:07:23.703+0530 [TRACE] plugin.terraform-provider-google_v4.78.0_x5: Sending request downstream: @module=sdk.proto tf_proto_version=5.3 tf_provider_addr=registry.terraform.io/hashicorp/google tf_req_id=be675dfe-90f2-606b-f9a3-aca736bbc328 @caller=github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/internal/tf5serverlogging/downstream_request.go:17 tf_rpc=ReadResource tf_resource_type=google_container_node_pool timestamp="2023-08-16T14:07:23.702+0530"
2023-08-16T14:07:23.706+0530 [DEBUG] plugin.terraform-provider-google_v4.78.0_x5: panic: interface conversion: interface {} is nil, not *transport.Config
2023-08-16T14:07:23.706+0530 [DEBUG] plugin.terraform-provider-google_v4.78.0_x5:
2023-08-16T14:07:23.706+0530 [DEBUG] plugin.terraform-provider-google_v4.78.0_x5: goroutine 197 [running]:
2023-08-16T14:07:23.706+0530 [DEBUG] plugin.terraform-provider-google_v4.78.0_x5: github.com/hashicorp/terraform-provider-google/google/services/container.resourceContainerNodePoolExists(0x4a8f3b8?, {0x0?, 0x0?})
2023-08-16T14:07:23.706+0530 [DEBUG] plugin.terraform-provider-google_v4.78.0_x5: 	github.com/hashicorp/terraform-provider-google/google/services/container/resource_container_node_pool.go:756 +0x58d
2023-08-16T14:07:23.706+0530 [DEBUG] plugin.terraform-provider-google_v4.78.0_x5: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc000dc3a40, {0x4a8f3b8, 0xc001024810}, 0xc000cc0340, {0x0, 0x0})
2023-08-16T14:07:23.706+0530 [DEBUG] plugin.terraform-provider-google_v4.78.0_x5: 	github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.0/helper/schema/resource.go:992 +0x397
2023-08-16T14:07:23.706+0530 [DEBUG] plugin.terraform-provider-google_v4.78.0_x5: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0xc000e7d368, {0x4a8f3b8?, 0xc0010246f0?}, 0xc00167b6c0)
2023-08-16T14:07:23.706+0530 [DEBUG] plugin.terraform-provider-google_v4.78.0_x5: 	github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.0/helper/schema/grpc_provider.go:613 +0x4a5
2023-08-16T14:07:23.706+0530 [DEBUG] plugin.terraform-provider-google_v4.78.0_x5: github.com/hashicorp/terraform-plugin-mux/tf5muxserver.muxServer.ReadResource({0xc000e349c0, 0xc000e34a20, {0xc0010f01c0, 0x2, 0x2}, {0x0, 0x0, 0x0}, {0x0, 0x0, ...}, ...}, ...)
2023-08-16T14:07:23.706+0530 [DEBUG] plugin.terraform-provider-google_v4.78.0_x5: 	github.com/hashicorp/terraform-plugin-mux@v0.8.0/tf5muxserver/mux_server_ReadResource.go:26 +0x102
2023-08-16T14:07:23.706+0530 [DEBUG] plugin.terraform-provider-google_v4.78.0_x5: github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ReadResource(0xc00021f860, {0x4a8f3b8?, 0xc000ffb830?}, 0xc00127a2a0)
2023-08-16T14:07:23.706+0530 [DEBUG] plugin.terraform-provider-google_v4.78.0_x5: 	github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/tf5server/server.go:748 +0x4b1
2023-08-16T14:07:23.706+0530 [DEBUG] plugin.terraform-provider-google_v4.78.0_x5: github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler({0x430c980?, 0xc00021f860}, {0x4a8f3b8, 0xc000ffb830}, 0xc00138a000, 0x0)
2023-08-16T14:07:23.706+0530 [DEBUG] plugin.terraform-provider-google_v4.78.0_x5: 	github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:349 +0x170
2023-08-16T14:07:23.706+0530 [DEBUG] plugin.terraform-provider-google_v4.78.0_x5: google.golang.org/grpc.(*Server).processUnaryRPC(0xc000f70b40, {0x4a983c0, 0xc001216680}, 0xc000c846c0, 0xc0014d0000, 0x621a5b0, 0x0)
2023-08-16T14:07:23.706+0530 [DEBUG] plugin.terraform-provider-google_v4.78.0_x5: 	google.golang.org/grpc@v1.56.2/server.go:1337 +0xdf0
2023-08-16T14:07:23.706+0530 [DEBUG] plugin.terraform-provider-google_v4.78.0_x5: google.golang.org/grpc.(*Server).handleStream(0xc000f70b40, {0x4a983c0, 0xc001216680}, 0xc000c846c0, 0x0)
2023-08-16T14:07:23.706+0530 [DEBUG] plugin.terraform-provider-google_v4.78.0_x5: 	google.golang.org/grpc@v1.56.2/server.go:1714 +0xa2f
2023-08-16T14:07:23.706+0530 [DEBUG] plugin.terraform-provider-google_v4.78.0_x5: google.golang.org/grpc.(*Server).serveStreams.func1.1()
2023-08-16T14:07:23.706+0530 [DEBUG] plugin.terraform-provider-google_v4.78.0_x5: 	google.golang.org/grpc@v1.56.2/server.go:959 +0x98
2023-08-16T14:07:23.706+0530 [DEBUG] plugin.terraform-provider-google_v4.78.0_x5: created by google.golang.org/grpc.(*Server).serveStreams.func1
2023-08-16T14:07:23.706+0530 [DEBUG] plugin.terraform-provider-google_v4.78.0_x5: 	google.golang.org/grpc@v1.56.2/server.go:957 +0x18c
2023-08-16T14:07:23.709+0530 [ERROR] plugin: plugin process exited: path=.terraform/providers/registry.terraform.io/hashicorp/google/4.78.0/darwin_amd64/terraform-provider-google_v4.78.0_x5 pid=27587 error="exit status 2"

**Comment by AndrzejKomarnicki** [comment]
Also having issues with GCP provider

2023-08-22T16:07:38.634-0400 [ERROR] plugin.terraform-provider-google_v4.78.0_x5: Response contains error diagnostic: @module=sdk.proto tf_provider_addr=registry.terraform.io/hashicorp/google tf_req_id=e3513184-a0ab-4dd2-483a-f11c1ba7ab1d diagnostic_attribute=""
  diagnostic_detail=
  | An unexpected error was encountered trying to build a value. This is always an error in the provider. Please report the following to the provider developer:
  | 
  | Received null value, however the target type cannot handle null values. Use the corresponding `types` package type, a pointer type or a custom type that handles null values.
  | 
  | Path: 
  | Target Type: fwmodels.ProviderModel
  | Suggested `types` Type: basetypes.ObjectValue
  | Suggested Pointer Type: *fwmodels.ProviderModel
   diagnostic_severity=ERROR diagnostic_summary="Value Conversion Error" tf_proto_version=5.3 tf_rpc=Configure @caller=github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/internal/diag/diagnostics.go:55 timestamp=2023-08-22T16:07:38.634-0400


2023-08-22T16:07:50.763-0400 [ERROR] plugin: plugin process exited: path=.terraform/providers/registry.terraform.io/hashicorp/google/4.78.0/darwin_arm64/terraform-provider-google_v4.78.0_x5 pid=52595 error="exit status 2"
2023/08/22 16:07:50 rpc error: code = Unavailable desc = error reading from server: EOF
2023/08/22 16:07:50 rpc error: code = Unavailable desc = error reading from server: EOF
2023/08/22 16:07:50 WARN: Fail read resource from provider, wait 300ms before retry
2023/08/22 16:07:50 rpc error: code = Unavailable desc = error reading from server: EOF
2023/08/22 16:07:50 WARN: Fail read resource from provider, wait 300ms before retry
2023/08/22 16:07:50 rpc error: code = Unavailable desc = error reading from server: EOF
2023/08/22 16:07:50 WARN: Fail read resource from provider, wait 300ms before retry
2023/08/22 16:07:50 rpc error: code = Unavailable desc = error reading from server: EOF
2023/08/22 16:07:50 rpc error: code = Unavailable desc = error reading from server: EOF
2023/08/22 16:07:50 rpc error: code = Unavailable desc = error reading from server: EOF
2023/08/22 16:07:50 rpc error: code = Unavailable desc = error reading from server: EOF
2023/08/22 16:07:50 WARN: Fail read resource from provider, wait 300ms before retry
2023/08/22 16:07:50 WARN: Fail read resource from provider, wait 300ms before retry
2023/08/22 16:07:50 rpc error: code = Unavailable desc = error reading from server: EOF
2023/08/22 16:07:50 WARN: Fail read resource from provider, wait 300ms before retry
2023/08/22 16:07:50 WARN: Fail read resource from provider, wait 300ms before retry
2023/08/22 16:07:50 rpc error: code = Unavailable desc = error reading from server: EOF
2023/08/22 16:07:50 WARN: Fail read resource from provider, wait 300ms before retry
2023/08/22 16:07:50 rpc error: code = Unavailable desc = error reading from server: EOF
2023/08/22 16:07:50 WARN: Fail read resource from provider, wait 300ms before retry
2023/08/22 16:07:50 rpc error: code = Unavailable desc = error reading from server: EOF
2023/08/22 16:07:50 WARN: Fail read resource from provider, wait 300ms before retry
2023/08/22 16:07:50 rpc error: code = Unavailable desc = error reading from server: EOF
2023/08/22 16:07:50 WARN: Fail read resource from provider, wait 300ms before retry
2023/08/22 16:07:50 rpc error: code = Unavailable desc = error reading from server: EOF
2023/08/22 16:07:50 WARN: Fail read resource from provider, wait 300ms before retry
2023/08/22 16:07:50 WARN: Fail read resource from provider, wait 300ms before retry
2023/08/22 16:07:50 rpc error: code = Unavailable desc = error reading from server: EOF
2023/08/22 16:07:50 WARN: Fail read resource from provider, wait 300ms before retry
2023/08/22 16:07:50 WARN: Fail read resource from provider, wait 300ms before retry
2023/08/22 16:07:51 rpc error: code = Canceled desc = context canceled
2023/08/22 16:07:51 WARN: Fail read resource from provider, wait 300ms before retry
2023/08/22 16:07:51 rpc error: code = Canceled desc = context canceled
2023/08/22 16:07:51 WARN: Fail read resource from provider, wait 300ms before retry
2023/08/22 16:07:51 rpc error: code = Canceled desc = context canceled
2023/08/22 16:07:51 WARN: Fail read resource from provider, wait 300ms before retry
2023/08/22 16:07:51 rpc error: code = Canceled desc = context canceled
2023/08/22 16:07:51 WARN: Fail read resource from provider, wait 300ms before retry
2023/08/22 16:07:51 rpc error: code = Canceled desc = context canceled
2023/08/22 16:07:51 WARN: Fail read resource from provider, wait 300ms before retry
2023/08/22 16:07:51 rpc error: code = Canceled desc = context canceled
2023/08/22 16:07:51 WARN: Fail read resource from provider, wait 300ms before retry
2023/08/22 16:07:51 rpc error: code = Canceled desc = context canceled
2023/08/22 16:07:51 WARN: Fail read resource from provider, wait 300ms before retry
2023/08/22 16:07:51 rpc error: code = Canceled desc = context canceled
2023/08/22 16:07:51 WARN: Fail read resource from provider, wait 300ms before retry

**Comment by siba-prosimo** [comment]
Looks like terraformer does not have support for latest provider releases, I was able to make the import work with version "4.59.0".

**Comment by MaxDaten** [comment]
Would not close this as this is still a problem and switching to version 4.59.0 is just a workaround

**Comment by AhmedKamal20** [comment]
Worked for me on version 7.20.0
