### ISSUE TITLE
Error `index out of range [0] with length 0` for identitystore

### ISSUE THREAD

**Issue by ioah86** [GoogleCloudPlatform/terraformer#1808]
Terraformer version: 0.8.24
Terraform version: 1.6.4
Architecture: Centos 8

It appears that there is an index out of bounds error if the identitystore is empty.

```
terraformer import aws '--resources=*' --regions=ap-south-1 --retry-number=1 --retry-sleep-ms=10
2023/11/24 20:19:38 aws importing region ap-south-1
2023/11/24 20:19:38 Attempting an import of ALL resources in aws
2023/11/24 20:19:40 aws importing... accessanalyzer
2023/11/24 20:19:40 aws error initializing resources in service accessanalyzer, err: operation error AccessAnalyzer: ListAnalyzers, failed to resolve service endpoint, an AWS region is required, but was not found
2023/11/24 20:19:40 aws importing... acm
2023/11/24 20:19:42 aws done importing acm
2023/11/24 20:19:42 aws importing... alb
2023/11/24 20:19:44 aws done importing alb
2023/11/24 20:19:44 aws importing... api_gateway
2023/11/24 20:19:46 aws done importing api_gateway
2023/11/24 20:19:46 aws importing... appsync
2023/11/24 20:19:47 aws done importing appsync
2023/11/24 20:19:47 aws importing... auto_scaling
2023/11/24 20:19:51 aws done importing auto_scaling
2023/11/24 20:19:51 aws importing... batch
2023/11/24 20:19:52 aws done importing batch
2023/11/24 20:19:52 aws importing... budgets
2023/11/24 20:19:54 aws done importing budgets
2023/11/24 20:19:54 aws importing... cloud9
2023/11/24 20:19:55 aws done importing cloud9
2023/11/24 20:19:55 aws importing... cloudformation
2023/11/24 20:19:57 aws done importing cloudformation
2023/11/24 20:19:57 aws importing... cloudfront
2023/11/24 20:19:57 aws done importing cloudfront
2023/11/24 20:19:57 aws importing... cloudhsm
2023/11/24 20:19:59 aws done importing cloudhsm
2023/11/24 20:19:59 aws importing... cloudtrail
2023/11/24 20:20:01 aws done importing cloudtrail
2023/11/24 20:20:01 aws importing... cloudwatch
2023/11/24 20:20:04 aws done importing cloudwatch
2023/11/24 20:20:04 aws importing... codebuild
2023/11/24 20:20:05 aws done importing codebuild
2023/11/24 20:20:05 aws importing... codecommit
2023/11/24 20:20:06 aws done importing codecommit
2023/11/24 20:20:06 aws importing... codedeploy
2023/11/24 20:20:07 aws done importing codedeploy
2023/11/24 20:20:07 aws importing... codepipeline
2023/11/24 20:20:09 aws done importing codepipeline
2023/11/24 20:20:09 aws importing... cognito
2023/11/24 20:20:11 aws done importing cognito
2023/11/24 20:20:11 aws importing... config
2023/11/24 20:20:14 aws done importing config
2023/11/24 20:20:14 aws importing... customer_gateway
2023/11/24 20:20:15 aws done importing customer_gateway
2023/11/24 20:20:15 aws importing... datapipeline
2023/11/24 20:20:19 aws done importing datapipeline
2023/11/24 20:20:19 aws importing... devicefarm
2023/11/24 20:20:23 aws done importing devicefarm
2023/11/24 20:20:23 aws importing... docdb
2023/11/24 20:20:26 aws done importing docdb
2023/11/24 20:20:26 aws importing... dynamodb
2023/11/24 20:20:27 aws done importing dynamodb
2023/11/24 20:20:27 aws importing... ebs
2023/11/24 20:20:28 aws done importing ebs
2023/11/24 20:20:28 aws importing... ec2_instance
2023/11/24 20:20:30 aws done importing ec2_instance
2023/11/24 20:20:30 aws importing... ecr
2023/11/24 20:20:32 aws done importing ecr
2023/11/24 20:20:32 aws importing... ecrpublic
2023/11/24 20:20:32 aws done importing ecrpublic
2023/11/24 20:20:32 aws importing... ecs
2023/11/24 20:20:34 aws done importing ecs
2023/11/24 20:20:34 aws importing... efs
2023/11/24 20:20:36 aws done importing efs
2023/11/24 20:20:36 aws importing... eip
2023/11/24 20:20:37 aws done importing eip
2023/11/24 20:20:37 aws importing... eks
2023/11/24 20:20:39 aws done importing eks
2023/11/24 20:20:39 aws importing... elastic_beanstalk
2023/11/24 20:20:41 aws done importing elastic_beanstalk
2023/11/24 20:20:41 aws importing... elasticache
2023/11/24 20:20:43 aws done importing elasticache
2023/11/24 20:20:43 aws importing... elb
2023/11/24 20:20:44 aws done importing elb
2023/11/24 20:20:44 aws importing... emr
2023/11/24 20:20:46 aws done importing emr
2023/11/24 20:20:46 aws importing... eni
2023/11/24 20:20:47 aws done importing eni
2023/11/24 20:20:47 aws importing... es
2023/11/24 20:20:48 aws done importing es
2023/11/24 20:20:48 aws importing... firehose
2023/11/24 20:20:50 aws done importing firehose
2023/11/24 20:20:50 aws importing... glue
2023/11/24 20:20:53 aws done importing glue
2023/11/24 20:20:53 aws importing... iam
2023/11/24 20:20:55 aws done importing iam
2023/11/24 20:20:55 aws importing... identitystore
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/GoogleCloudPlatform/terraformer/providers/aws.(*IdentityStoreGenerator).GetIdentityStoreId(0xc000ac90d0?)
	/Users/sergey/temp/terraformer/providers/aws/identitystore.go:44 +0x1ce
github.com/GoogleCloudPlatform/terraformer/providers/aws.(*IdentityStoreGenerator).InitResources(0x0?)
	/Users/sergey/temp/terraformer/providers/aws/identitystore.go:169 +0x25
github.com/GoogleCloudPlatform/terraformer/providers/aws.(*AwsFacade).InitResources(0xc0019e4550?)
	/Users/sergey/temp/terraformer/providers/aws/aws_facade.go:61 +0x26
github.com/GoogleCloudPlatform/terraformer/cmd.initServiceResources({_, _}, {_, _}, {{0xc000978000, 0x56, 0x80}, {0x85deae8, 0x0, 0x0}, ...}, ...)
	/Users/sergey/temp/terraformer/cmd/import.go:209 +0x21e
github.com/GoogleCloudPlatform/terraformer/cmd.initAllServicesResources(_, {{0xc000978000, 0x56, 0x80}, {0x85deae8, 0x0, 0x0}, {0x5de106f, 0x1e}, {0x5d73544, ...}, ...}, ...)
	/Users/sergey/temp/terraformer/cmd/import.go:166 +0x1c5
github.com/GoogleCloudPlatform/terraformer/cmd.Import({_, _}, {{0xc000978000, 0x56, 0x80}, {0x85deae8, 0x0, 0x0}, {0x5de106f, 0x1e}, ...}, ...)
	/Users/sergey/temp/terraformer/cmd/import.go:98 +0x2a5
github.com/GoogleCloudPlatform/terraformer/cmd.importRegionResources({{0xc000621e80, 0x1, 0x1}, {0x85deae8, 0x0, 0x0}, {0x5de106f, 0x1e}, {0x5d73544, 0x9}, ...}, ...)
	/Users/sergey/temp/terraformer/cmd/provider_cmd_aws.go:121 +0x292
github.com/GoogleCloudPlatform/terraformer/cmd.newCmdAwsImporter.func1(0xc00014bb80?, {0x5d69827?, 0x4?, 0x4?})
	/Users/sergey/temp/terraformer/cmd/provider_cmd_aws.go:58 +0xa0e
github.com/spf13/cobra.(*Command).execute(0xc00014bb80, {0xc000322d40, 0x4, 0x4})
	/Users/sergey/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:850 +0x67c
github.com/spf13/cobra.(*Command).ExecuteC(0xc00014b080)
	/Users/sergey/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:958 +0x39d
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/sergey/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:895
github.com/GoogleCloudPlatform/terraformer/cmd.Execute()
	/Users/sergey/temp/terraformer/cmd/root.go:36 +0x1e
main.main()
	/Users/sergey/temp/terraformer/main.go:39 +0x50
```

**Comment by vgavro** [comment]
fixed in #1815

**Comment by monelgordillo** [comment]
I had to exlude it too.

**Comment by persunde** [comment]
Experienced this issue using `version v0.8.24`
