### ISSUE TITLE
Error for alicloud  plugin: plugin process exited: path=.terraform/providers/registry.terraform.io/aliyun/alicloud/1.213.1/linux_amd64/terraform-provider-alicloud_v1.213.1 pid=7403 error="exit status 2"

### ISSUE THREAD

**Issue by YuPengZhangL** [GoogleCloudPlatform/terraformer#1819]
# Example:
- terraformer  import alicloud --profile=default  --resources=ecs --regions=us-west-1  --path-output=/data/deploy/terraformer/alicloud/ --path-pattern={output}/ecs/ --output=json
- terraformer  import alicloud --profile=default  --resources=sg --regions=us-west-1  --path-output=/data/deploy/terraformer/alicloud/ --path-pattern={output}/sg/ --output=json
# Output:
2023/12/13 10:30:26 Refreshing state... alicloud_instance.tfer--i-rj97vwjyj7phlioiqyom__d3-gb-backup_01
2023-12-13T10:30:26.835+0800 [ERROR] plugin: plugin process exited: path=.terraform/providers/registry.terraform.io/aliyun/alicloud/1.213.1/linux_amd64/terraform-provider-alicloud_v1.213.1 pid=7403 error="exit status 2"
2023/12/13 10:30:26 rpc error: code = Unavailable desc = error reading from server: read unix @->/tmp/plugin3688382484: read: connection reset by peer
2023/12/13 10:30:26 WARN: Fail read resource from provider, wait 300ms before retry
2023/12/13 14:09:37 Fail read resource from provider, trying import command
2023/12/13 14:09:37 rpc error: code = Canceled desc = context canceled
2023/12/13 14:09:37 ERROR: Unable to refresh resource tfer--i-rj97vwjyj7phlioiqyom__d3-gb-backup_01
2023/12/13 14:09:37 ERROR: Unable to refresh resource tfer--i-rj98p62w4un5iuafbjsl__gtp-us-golang_01
2023/12/13 14:09:37 ERROR: Unable to refresh resource tfer--i-rj9bnqluaft9mzcp4roz__d3-gb-proxy
2023/12/13 14:09:37 ERROR: Unable to refresh resource tfer--i-rj903nvuev5sr2l909p5__wol-gb-proxy_01
2023/12/13 14:09:37 ERROR: Unable to refresh resource tfer--i-rj9j2slvu1rtbq33ee8w__gtp-us-control
2023/12/13 14:09:37 ERROR: Unable to refresh resource tfer--i-rj9ej7fijadw65iwujp0__d3-gb-platform-db-slave_01
2023/12/13 14:09:37 ERROR: Unable to refresh resource tfer--i-rj997x28sq0e2zs7gs2h__snd-gb-ea-prometheus
2023/12/13 14:09:37 ERROR: Unable to refresh resource tfer--i-rj90d2fv5yn81lhf5tq9__gtp-us-docker-goatkeeper_02
2023/12/13 14:09:37 ERROR: Unable to refresh resource tfer--i-rj93uuv7kln93qi13ili__snd-gb-ea-common
2023/12/13 14:09:37 ERROR: Unable to refresh resource tfer--i-rj93ic8g4x6ab5ojqhoi__d3-gb-windows-jumpserver
2023/12/13 14:09:37 ERROR: Unable to refresh resource tfer--i-rj9e7abwhdokw2xgw1pm__gtp-us-etcd_02
2023/12/13 14:09:37 ERROR: Unable to refresh resource tfer--i-rj9bnqluaft9ltx1rm4e__d3-gb-game-db_01
2023/12/13 14:09:37 ERROR: Unable to refresh resource tfer--i-rj9fmq9tqymh3ojb11v5__gtp-us-golang_03
2023/12/13 14:09:37 ERROR: Unable to refresh resource tfer--i-rj9ej7fijadw65iwujoz__d3-gb-login-db-slave_01
2023/12/13 14:09:37 ERROR: Unable to refresh resource tfer--i-rj9brdwoewy96i1nmxs0__d3-gb-platform_02
2023/12/13 14:09:37 ERROR: Unable to refresh resource tfer--i-rj95ksdxe2nt2bxbebem__d3-gb-login_02
2023/12/13 14:09:37 ERROR: Unable to refresh resource tfer--i-rj9135dwgf3frg6fzksu__gtp-us-docker-goatkeeper_03
2023/12/13 14:09:37 ERROR: Unable to refresh resource tfer--i-rj90d2fv5yn81lhf5tqa__gtp-us-golang_02
2023/12/13 14:09:37 ERROR: Unable to refresh resource tfer--i-rj9e7abwhdokw2xgw1pn__gtp-us-etcd_03
2023/12/13 14:09:37 ERROR: Unable to refresh resource tfer--i-rj9bnqluaft9ltx1rm49__d3-gb-login-db_01
2023/12/13 14:09:37 ERROR: Unable to refresh resource tfer--i-rj9bnqluaft9ltx1rm4b__d3-gb-shenhe_01
2023/12/13 14:09:37 ERROR: Unable to refresh resource tfer--i-rj9acgm9w7vlxnpznrty__d3-gb-platform_03
2023/12/13 14:09:37 ERROR: Unable to refresh resource tfer--i-rj9fk49a82803d4v7hmo__snd-gb-ea-game
2023/12/13 14:09:37 ERROR: Unable to refresh resource tfer--i-rj9gvp0f8j6tlmiqw62d__wol-gb-cron_0001
2023/12/13 14:09:37 ERROR: Unable to refresh resource tfer--i-rj96j8s1qx4hqn2492ze__snd-gb-ea-control
2023/12/13 14:09:37 ERROR: Unable to refresh resource tfer--i-rj9acgm9w7vlt7whjaur__d3-gb-point_01
2023/12/13 14:09:37 ERROR: Unable to refresh resource tfer--i-rj9gvp0f8j6tlmiqw62b__wol-gb-game_0001
2023/12/13 14:09:37 ERROR: Unable to refresh resource tfer--i-rj9gvp0f8j6tlmiqw62c__wol-gb-game_0002
2023/12/13 14:09:37 ERROR: Unable to refresh resource tfer--i-rj9anwzy6olg4ifmgjs6__gtp-us-etcd_01
2023/12/13 14:09:37 ERROR: Unable to refresh resource tfer--i-rj9bnqluaft9ltx1rm48__d3-gb-gm_01
2023/12/13 14:09:37 ERROR: Unable to refresh resource tfer--i-rj9ej7fijadyl0uwds8y__d3-gb-monitor_01
2023/12/13 14:09:37 ERROR: Unable to refresh resource tfer--i-rj9bnqluaft9ltx1rm4a__d3-gb-game_01
2023/12/13 14:09:37 ERROR: Unable to refresh resource tfer--i-rj9135dwgf3frg6fzkst__gtp-us-golang_04
2023/12/13 14:09:37 ERROR: Unable to refresh resource tfer--i-rj9bnqluaft9ltx1rm4c__d3-gb-login_01
2023/12/13 14:09:37 ERROR: Unable to refresh resource tfer--i-rj90d2fv5yn81lhf5tqb__gtp-us-golang_pre
2023/12/13 14:09:37 ERROR: Unable to refresh resource tfer--i-rj98p62w4un5iuafbjsm__gtp-us-docker-goatkeeper_01
2023/12/13 14:09:37 ERROR: Unable to refresh resource tfer--i-rj9bnqluaft9ltx1rm4d__d3-gb-platform_01
2023/12/13 14:09:37 ERROR: Unable to refresh resource tfer--i-rj9gjasnnorrx4v5rm9b__d3-gb-log_01
2023/12/13 14:09:37 ERROR: Unable to refresh resource tfer--i-rj927hto2vnjorksrhch__gtp-us-sandbox_01
2023/12/13 14:09:37 ERROR: Unable to refresh resource tfer--i-rj9ej7fijadw65iwujp1__d3-gb-game-db-slave_01
2023/12/13 14:09:37 Filtered number of resources for service ecs: 0
2023/12/13 14:09:37 alicloud Connecting....
2023/12/13 14:09:37 alicloud save
2023/12/13 14:09:37 alicloud save tfstate

**Comment by YuPengZhangL** [comment]
# use verbose debug error
2023-12-13T15:29:15.398+0800 [DEBUG] plugin.terraform-provider-alicloud_v1.213.1: panic: interface conversion: interface {} is nil, not *connectivity.AliyunClient
2023-12-13T15:29:15.398+0800 [DEBUG] plugin.terraform-provider-alicloud_v1.213.1:
2023-12-13T15:29:15.398+0800 [DEBUG] plugin.terraform-provider-alicloud_v1.213.1: goroutine 69 [running]:
2023-12-13T15:29:15.398+0800 [DEBUG] plugin.terraform-provider-alicloud_v1.213.1: github.com/aliyun/terraform-provider-alicloud/alicloud.resourceAliCloudInstanceRead(0xc0029d69a0?, {0x0?, 0x0?})
2023-12-13T15:29:15.398+0800 [DEBUG] plugin.terraform-provider-alicloud_v1.213.1: 	github.com/aliyun/terraform-provider-alicloud/alicloud/resource_alicloud_instance.go:966 +0x3497
2023-12-13T15:29:15.398+0800 [DEBUG] plugin.terraform-provider-alicloud_v1.213.1: github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc000f8b540, 0xc002a34230, {0x0, 0x0})
2023-12-13T15:29:15.398+0800 [DEBUG] plugin.terraform-provider-alicloud_v1.213.1: 	github.com/hashicorp/terraform-plugin-sdk@v1.17.2/helper/schema/resource.go:470 +0x1aa
2023-12-13T15:29:15.398+0800 [DEBUG] plugin.terraform-provider-alicloud_v1.213.1: github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin.(*GRPCProviderServer).ReadResource(0xc0006ed870, {0xc0029c63c0?, 0x52a5c6?}, 0xc0029c63c0)
2023-12-13T15:29:15.398+0800 [DEBUG] plugin.terraform-provider-alicloud_v1.213.1: 	github.com/hashicorp/terraform-plugin-sdk@v1.17.2/internal/helper/plugin/grpc_provider.go:535 +0x34b
2023-12-13T15:29:15.398+0800 [DEBUG] plugin.terraform-provider-alicloud_v1.213.1: github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5._Provider_ReadResource_Handler({0x6fd4c00?, 0xc0006ed870}, {0x82a4060, 0xc002a0f590}, 0xc0029d64d0, 0x0)
2023-12-13T15:29:15.398+0800 [DEBUG] plugin.terraform-provider-alicloud_v1.213.1: 	github.com/hashicorp/terraform-plugin-sdk@v1.17.2/internal/tfplugin5/tfplugin5.pb.go:3269 +0x170
2023-12-13T15:29:15.398+0800 [DEBUG] plugin.terraform-provider-alicloud_v1.213.1: google.golang.org/grpc.(*Server).processUnaryRPC(0xc0000005a0, {0x82f72c8, 0xc0011891e0}, 0xc002a2c360, 0xc001d75920, 0xeef7050, 0x0)
2023-12-13T15:29:15.398+0800 [DEBUG] plugin.terraform-provider-alicloud_v1.213.1: 	google.golang.org/grpc@v1.56.3/server.go:1335 +0xde3
2023-12-13T15:29:15.398+0800 [DEBUG] plugin.terraform-provider-alicloud_v1.213.1: google.golang.org/grpc.(*Server).handleStream(0xc0000005a0, {0x82f72c8, 0xc0011891e0}, 0xc002a2c360, 0x0)
2023-12-13T15:29:15.398+0800 [DEBUG] plugin.terraform-provider-alicloud_v1.213.1: 	google.golang.org/grpc@v1.56.3/server.go:1712 +0xa1b
2023-12-13T15:29:15.398+0800 [DEBUG] plugin.terraform-provider-alicloud_v1.213.1: google.golang.org/grpc.(*Server).serveStreams.func1.1()
2023-12-13T15:29:15.398+0800 [DEBUG] plugin.terraform-provider-alicloud_v1.213.1: 	google.golang.org/grpc@v1.56.3/server.go:947 +0xca
2023-12-13T15:29:15.398+0800 [DEBUG] plugin.terraform-provider-alicloud_v1.213.1: created by google.golang.org/grpc.(*Server).serveStreams.func1
2023-12-13T15:29:15.399+0800 [DEBUG] plugin.terraform-provider-alicloud_v1.213.1: 	google.golang.org/grpc@v1.56.3/server.go:958 +0x15c
2023-12-13T15:29:15.409+0800 [ERROR] plugin: plugin process exited: path=.terraform/providers/registry.terraform.io/aliyun/alicloud/1.213.1/linux_amd64/terraform-provider-alicloud_v1.213.1 pid=7747 error="exit status 2"

**Comment by YuPengZhangL** [comment]
After reviewing the source code, I found that the Aliyun plugin version is 1.57.1. It seems to be incompatible now, so I can’t export all Aliyun resources
