### ISSUE TITLE
panic: unknown resource type google_compute_region_instance_group

### ISSUE THREAD

**Issue by akamalov** [GoogleCloudPlatform/terraformer#1859]
*Environment:*

`MacOS Sonoma 14.4`
`Terraform v1.4.6`
`Terraformer v0.8.24`

*Issue:*

When running a command:

`$ terraformer import google --projects "test" --regions "us-east4" --resources="*"  `

...encountered an error:

```
panic: unknown resource type google_compute_region_instance_group

goroutine 1916 [running]:
github.com/hashicorp/terraform/plugin.(*GRPCProvider).getResourceSchema(0x140001ae900?, {0x10c4ceece, 0x24})
	github.com/hashicorp/terraform@v0.12.31/plugin/grpc_provider.go:92 +0xc8
github.com/hashicorp/terraform/plugin.(*GRPCProvider).ReadResource(0x14000ae32d0, {{0x10c4ceece, 0x24}, {{{0x10f8157c8, 0x14000844c70}}, {0x10e11adc0, 0x14002ac60c0}}, {0x115f03300, 0x0, 0x0}})
	github.com/hashicorp/terraform@v0.12.31/plugin/grpc_provider.go:321 +0xbc
github.com/GoogleCloudPlatform/terraformer/terraformutils/providerwrapper.(*ProviderWrapper).Refresh(0x14000adae70, 0x140028dfbd0, 0x140028dfb80)
	github.com/GoogleCloudPlatform/terraformer/terraformutils/providerwrapper/provider.go:171 +0x318
github.com/GoogleCloudPlatform/terraformer/terraformutils.(*Resource).Refresh(0x14002d2a240, 0x0?)
	github.com/GoogleCloudPlatform/terraformer/terraformutils/resource.go:130 +0x50
github.com/GoogleCloudPlatform/terraformer/terraformutils.RefreshResourceWorker(0x0?, 0x104b97860?, 0x14002606720?)
	github.com/GoogleCloudPlatform/terraformer/terraformutils/utils.go:153 +0xc8
created by github.com/GoogleCloudPlatform/terraformer/terraformutils.RefreshResources in goroutine 1
	github.com/GoogleCloudPlatform/terraformer/terraformutils/utils.go:80 +0xb4

```

**Comment by akamalov** [comment]
I also tried with beta provider support, I am getting the same error.
