### ISSUE TITLE
Azurerm - getting error importing any supported resources 

### ISSUE THREAD

**Issue by raj-11** [GoogleCloudPlatform/terraformer#600]
Getting Fail read resource from provider for all suported resources for Azure.

terraformer import azure -r virtual_machine
.
.
2020/09/03 00:45:22 azurerm importing... virtual_machine
2020/09/03 00:45:23 Refreshing state... azurerm_linux_virtual_machine.tfer--<machine name>
2020/09/03 00:45:23 WARN: Fail read resource from provider, wait 300ms before retry
2020/09/03 00:45:23 WARN: Fail read resource from provider, wait 300ms before retry
2020/09/03 00:45:24 WARN: Fail read resource from provider, wait 300ms before retry
2020/09/03 00:45:24 WARN: Fail read resource from provider, wait 300ms before retry
2020/09/03 00:45:24 WARN: Fail read resource from provider, wait 300ms before retry
2020/09/03 00:45:24 Fail read resource from provider, trying import command
2020/09/03 00:45:24 rpc error: code = Canceled desc = context canceled
2020/09/03 00:45:24 ERROR: Unable to refresh resource tfer--<machine name>
2020/09/03 00:45:24 azurerm Connecting....
2020/09/03 00:45:24 azurerm save virtual_machine
2020/09/03 00:45:25 azurerm save tfstate for virtual_machine

**Comment by snerdish** [comment]
Also seeing exactly this. Could it be a permissions issue? Running -v gives a lot of output claiming  "The client ... does not have authorization to perform action ... ", but I'm not sure what exactly it might be failing on. Currently running a tight set permssions for this directory. I can provide a scrubbed verbose output if needed.

**Comment by snerdish** [comment]
Could be related to https://github.com/GoogleCloudPlatform/terraformer/issues/614 ?

**Comment by snerdish** [comment]
A slightly more detailed trace - terraform is panicing, but I can't see why.


```
2020/11/19 14:45:36 azurerm importing... resource_group
2020/11/19 14:45:37 Refreshing state... azurerm_resource_group.tfer--Infrastructure
2020-11-19T14:45:37.155+1000 [DEBUG] plugin.terraform-provider-azurerm_v2.34.0_x5: panic: interface conversion: interface {} is nil, not *clients.Client
2020-11-19T14:45:37.155+1000 [DEBUG] plugin.terraform-provider-azurerm_v2.34.0_x5:
2020-11-19T14:45:37.155+1000 [DEBUG] plugin.terraform-provider-azurerm_v2.34.0_x5: goroutine 336 [running]:
2020-11-19T14:45:37.155+1000 [DEBUG] plugin.terraform-provider-azurerm_v2.34.0_x5: github.com/terraform-providers/terraform-provider-azurerm/azurerm/internal/services/resource.resourceArmResourceGroupRead(0xc0009d1420, 0x0, 0x0, 0x0, 0x0)
2020-11-19T14:45:37.155+1000 [DEBUG] plugin.terraform-provider-azurerm_v2.34.0_x5:      /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/azurerm/internal/services/resource/resource_arm_resource_group.go:91 +0x699
2020-11-19T14:45:37.155+1000 [DEBUG] plugin.terraform-provider-azurerm_v2.34.0_x5: github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc000ad0240, 0xc000ecf5e0, 0x0, 0x0, 0xc001122ea0, 0xc000ecf5e0, 0x0)
2020-11-19T14:45:37.155+1000 [DEBUG] plugin.terraform-provider-azurerm_v2.34.0_x5:      /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-sdk/helper/schema/resource.go:460 +0x119
2020-11-19T14:45:37.155+1000 [DEBUG] plugin.terraform-provider-azurerm_v2.34.0_x5: github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin.(*GRPCProviderServer).ReadResource(0xc00000f160, 0x5353b60, 0xc001122900, 0xc0014916e0, 0xc00000f160, 0xc001122900, 0xc00132bb78)
2020-11-19T14:45:37.155+1000 [DEBUG] plugin.terraform-provider-azurerm_v2.34.0_x5:      /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin/grpc_provider.go:525 +0x3d8
2020-11-19T14:45:37.155+1000 [DEBUG] plugin.terraform-provider-azurerm_v2.34.0_x5: github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5._Provider_ReadResource_Handler(0x47f8440, 0xc00000f160, 0x5353b60, 0xc001122900, 0xc001491680, 0x0, 0x5353b60, 0xc001122900, 0xc0002aa540, 0xb3)
2020-11-19T14:45:37.155+1000 [DEBUG] plugin.terraform-provider-azurerm_v2.34.0_x5:      /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5/tfplugin5.pb.go:3269 +0x217
2020-11-19T14:45:37.155+1000 [DEBUG] plugin.terraform-provider-azurerm_v2.34.0_x5: google.golang.org/grpc.(*Server).processUnaryRPC(0xc0000b9c80, 0x53953e0, 0xc0014fa600, 0xc0011b9e00, 0xc0009cda70, 0x8443870, 0x0, 0x0, 0x0)
2020-11-19T14:45:37.155+1000 [DEBUG] plugin.terraform-provider-azurerm_v2.34.0_x5:      /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:1024 +0x501
2020-11-19T14:45:37.155+1000 [DEBUG] plugin.terraform-provider-azurerm_v2.34.0_x5: google.golang.org/grpc.(*Server).handleStream(0xc0000b9c80, 0x53953e0, 0xc0014fa600, 0xc0011b9e00, 0x0)
2020-11-19T14:45:37.155+1000 [DEBUG] plugin.terraform-provider-azurerm_v2.34.0_x5:      /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:1313 +0xd3d
2020-11-19T14:45:37.155+1000 [DEBUG] plugin.terraform-provider-azurerm_v2.34.0_x5: google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc00051e270, 0xc0000b9c80, 0x53953e0, 0xc0014fa600, 0xc0011b9e00)
2020-11-19T14:45:37.155+1000 [DEBUG] plugin.terraform-provider-azurerm_v2.34.0_x5:      /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:722 +0xa1
2020-11-19T14:45:37.155+1000 [DEBUG] plugin.terraform-provider-azurerm_v2.34.0_x5: created by google.golang.org/grpc.(*Server).serveStreams.func1
2020-11-19T14:45:37.155+1000 [DEBUG] plugin.terraform-provider-azurerm_v2.34.0_x5:      /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:720 +0xa1
2020-11-19T14:45:37.159+1000 [DEBUG] plugin: plugin process exited: path=.terraform/plugins/registry.terraform.io/hashicorp/azurerm/2.34.0/linux_amd64/terraform-provider-azurerm_v2.34.0_x5 pid=18801 error="exit status 2"
2020/11/19 14:45:37 WARN: Fail read resource from provider, wait 300ms before retry
2020/11/19 14:45:37 WARN: Fail read resource from provider, wait 300ms before retry
2020/11/19 14:45:37 WARN: Fail read resource from provider, wait 300ms before retry
2020/11/19 14:45:38 WARN: Fail read resource from provider, wait 300ms before retry
2020/11/19 14:45:38 WARN: Fail read resource from provider, wait 300ms before retry
2020/11/19 14:45:38 Fail read resource from provider, trying import command
2020/11/19 14:45:38 rpc error: code = Canceled desc = context canceled
2020/11/19 14:45:38 ERROR: Unable to refresh resource tfer--Infrastructure

```

**Comment by cbuben** [comment]
Had a similar issue when trying to import resources in a subscription where I only had Contributor access to a single resource group. On a hunch, suspected this may be due to provider registration in the azurerm provider and limited access at subscription scope. Setting `ARM_SKIP_PROVIDER_REGISTRATION=true` environment variable resolved the issue in my case; YMMV.
