### ISSUE TITLE
Azure dns zones and resources fail to import

### ISSUE THREAD

**Issue by rgershkovich** [GoogleCloudPlatform/terraformer#614]
Huge thanks for your work first of all!

Trying to import Azure dns resources fails for zones:
```
[DEBUG] plugin.terraform-provider-azurerm_v2.31.1_x5: panic: interface conversion: interface {} is nil, not *clients.Client
[DEBUG] plugin.terraform-provider-azurerm_v2.31.1_x5:
[DEBUG] plugin.terraform-provider-azurerm_v2.31.1_x5: goroutine 388 [running]:
[DEBUG] plugin.terraform-provider-azurerm_v2.31.1_x5: github.com/terraform-providers/terraform-provider-azurerm/azurerm/internal/services/dns.resourceArmDnsZoneRead(0xc000a447e0, 0x0, 0x0, 0x0, 0x0)
[DEBUG] plugin.terraform-provider-azurerm_v2.31.1_x5:   /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/azurerm/internal/services/dns/dns_zone_resource.go:119 +0x754
[DEBUG] plugin.terraform-provider-azurerm_v2.31.1_x5: github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc0008f2e10, 0xc00122e4b0, 0x0, 0x0, 0xc0014da5d0, 0xc00122e4b0, 0x0)
[DEBUG] plugin.terraform-provider-azurerm_v2.31.1_x5:   /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-sdk/helper/schema/resource.go:460 +0x119
[DEBUG] plugin.terraform-provider-azurerm_v2.31.1_x5: github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin.(*GRPCProviderServer).ReadResource(0xc00000f640, 0x5baf100, 0xc0011e5b60, 0xc0011bfaa0, 0xc00000f640, 0xc0011e5b60, 0xc0006d0b78)
[DEBUG] plugin.terraform-provider-azurerm_v2.31.1_x5:   /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin/grpc_provider.go:525 +0x3d8
[DEBUG] plugin.terraform-provider-azurerm_v2.31.1_x5: github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5._Provider_ReadResource_Handler(0x50e9220, 0xc00000f640, 0x5baf100, 0xc0011e5b60, 0xc0011bfa40, 0x0, 0x5baf100, 0xc0011e5b60, 0xc000865040, 0x129)
[DEBUG] plugin.terraform-provider-azurerm_v2.31.1_x5:   /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5/tfplugin5.pb.go:3269 +0x217
[DEBUG] plugin.terraform-provider-azurerm_v2.31.1_x5: google.golang.org/grpc.(*Server).processUnaryRPC(0xc000783e00, 0x5bed9e0, 0xc000702f00, 0xc000652d00, 0xc0007312f0, 0x8aba210, 0x0, 0x0, 0x0)
[DEBUG] plugin.terraform-provider-azurerm_v2.31.1_x5:   /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:1024 +0x501
[DEBUG] plugin.terraform-provider-azurerm_v2.31.1_x5: google.golang.org/grpc.(*Server).handleStream(0xc000783e00, 0x5bed9e0, 0xc000702f00, 0xc000652d00, 0x0)
[DEBUG] plugin.terraform-provider-azurerm_v2.31.1_x5:   /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:1313 +0xd3d
[DEBUG] plugin.terraform-provider-azurerm_v2.31.1_x5: google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc000b2a2c0, 0xc000783e00, 0x5bed9e0, 0xc000702f00, 0xc000652d00)
[DEBUG] plugin.terraform-provider-azurerm_v2.31.1_x5:   /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:722 +0xa1
[DEBUG] plugin.terraform-provider-azurerm_v2.31.1_x5: created by google.golang.org/grpc.(*Server).serveStreams.func1
2020-10-11T00:42:40.398+0300 [DEBUG] plugin.terraform-provider-azurerm_v2.31.1_x5:  /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:720 +0xa1
```

... and records:

```
[DEBUG] plugin.terraform-provider-azurerm_v2.31.1_x5: panic: interface conversion: interface {} is nil, not *clients.Client
[DEBUG] plugin.terraform-provider-azurerm_v2.31.1_x5:
[DEBUG] plugin.terraform-provider-azurerm_v2.31.1_x5: goroutine 395 [running]:
[DEBUG] plugin.terraform-provider-azurerm_v2.31.1_x5: github.com/terraform-providers/terraform-provider-azurerm/azurerm/internal/services/dns.resourceArmDnsCNameRecordRead(0xc0003404d0, 0x0, 0x0, 0x0, 0x0)
[DEBUG] plugin.terraform-provider-azurerm_v2.31.1_x5:   /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/azurerm/internal/services/dns/dns_cname_record_resource.go:152 +0x84d
[DEBUG] plugin.terraform-provider-azurerm_v2.31.1_x5: github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc0008f2900, 0xc0011da230, 0x0, 0x0, 0xc0007b3920, 0xc0011da230, 0x0)
[DEBUG] plugin.terraform-provider-azurerm_v2.31.1_x5:   /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-sdk/helper/schema/resource.go:460 +0x119
[DEBUG] plugin.terraform-provider-azurerm_v2.31.1_x5: github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin.(*GRPCProviderServer).ReadResource(0xc00000f640, 0x5baf100, 0xc0007b2a20, 0xc001212a80, 0xc00000f640, 0xc0007b2a20, 0xc001d0bb78)
[DEBUG] plugin.terraform-provider-azurerm_v2.31.1_x5:   /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin/grpc_provider.go:525 +0x3d8
[DEBUG] plugin.terraform-provider-azurerm_v2.31.1_x5: github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5._Provider_ReadResource_Handler(0x50e9220, 0xc00000f640, 0x5baf100, 0xc0007b2a20, 0xc001212a20, 0x0, 0x5baf100, 0xc0007b2a20, 0xc00151a000, 0x12d)
[DEBUG] plugin.terraform-provider-azurerm_v2.31.1_x5:   /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5/tfplugin5.pb.go:3269 +0x217
[DEBUG] plugin.terraform-provider-azurerm_v2.31.1_x5: google.golang.org/grpc.(*Server).processUnaryRPC(0xc000783e00, 0x5bed9e0, 0xc000702f00, 0xc000653400, 0xc0007312f0, 0x8aba210, 0x0, 0x0, 0x0)
[DEBUG] plugin.terraform-provider-azurerm_v2.31.1_x5:   /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:1024 +0x501
[DEBUG] plugin.terraform-provider-azurerm_v2.31.1_x5: google.golang.org/grpc.(*Server).handleStream(0xc000783e00, 0x5bed9e0, 0xc000702f00, 0xc000653400, 0x0)
[DEBUG] plugin.terraform-provider-azurerm_v2.31.1_x5:   /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:1313 +0xd3d
[DEBUG] plugin.terraform-provider-azurerm_v2.31.1_x5: google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc000b2a2c0, 0xc000783e00, 0x5bed9e0, 0xc000702f00, 0xc000653400)
[DEBUG] plugin.terraform-provider-azurerm_v2.31.1_x5:   /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:722 +0xa1
[DEBUG] plugin.terraform-provider-azurerm_v2.31.1_x5: created by google.golang.org/grpc.(*Server).serveStreams.func1
[DEBUG] plugin.terraform-provider-azurerm_v2.31.1_x5:   /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:720 +0xa1
```

Tried with various versions of providers from v2.20.0 up to v2.31.1, getting the same result.

Non-debug log is not very helpful:
```
00:42:40 Refreshing state... azurerm_dns_zone.tfer--ats-002D-...
00:42:40 Refreshing state... azurerm_dns_ns_record.tfer---0040-
00:42:40 Refreshing state... azurerm_dns_a_record.tfer---0040-
00:42:40 Refreshing state... azurerm_dns_zone.tfer--aqua-002D-...
00:42:40 Refreshing state... azurerm_dns_ns_record.tfer---0040-
WARN: Fail read resource from provider, wait 300ms before retry
Fail read resource from provider, trying import command
rpc error: code = Canceled desc = context canceled
pid=92780 error="exit status 2"
```
This repeats without additional info.

**Comment by sergeylanzman** [comment]
Look like we you don't have meta in provider level
https://github.com/terraform-providers/terraform-provider-azurerm/blob/274c4b5b641d812f0805014a2e0fd8874d905afc/azurerm/internal/services/dns/dns_zone_resource.go#L70


You sure about provider installation on you machine? terraformer call to provider by default authorization, like envs or dot files

**Comment by snerdish** [comment]
Also seeing this. Same result with the recommended 2.20 and 2.34 (as automatically installed)

2020-11-04T10:01:25.127+1000 [DEBUG] plugin.terraform-provider-azurerm_v2.34.0_x5: panic: interface conversion: interface {} is nil, not *clients.Client
2020-11-04T10:01:25.127+1000 [DEBUG] plugin.terraform-provider-azurerm_v2.34.0_x5:
2020-11-04T10:01:25.127+1000 [DEBUG] plugin.terraform-provider-azurerm_v2.34.0_x5: goroutine 347 [running]:
2020-11-04T10:01:25.127+1000 [DEBUG] plugin.terraform-provider-azurerm_v2.34.0_x5: github.com/terraform-providers/terraform-provider-azurerm/azurerm/internal/services/compute.resourceLinuxVirtualMachineRead(0xc00128f570, 0x0, 0x0, 0x0, 0x0)

**Comment by rgershkovich** [comment]
I double-checked other resources like `resource_group` or `public_ip` and it looks like there are indeed issues on my side with the config.

There are 2 different subscriptions in my env, and one works well with all the resources, but the other (where DNS zones are) is failing in a similar way with resources that are known to work as well.

I have enough permissions to view or edit dns zones with web ui or `az network dns zone export -n xxx -g yyy`. I'd be grateful if you help me understand how to find the reason for this behaviour.

**Comment by snerdish** [comment]
I've been digging into this, and whilst I think it could be an issue with the terraform azurem provider I really don't have the cycles or chops to get much further.  Any hints welcome
