### ISSUE TITLE
Error importing externalVpnGateways - unknown resource type google_compute_external_vpn_gateway

### ISSUE THREAD

**Issue by JohnWillker** [GoogleCloudPlatform/terraformer#685]
I'm running the last terraformer(v0.8.9) version in Linux
I can import any resource except externalVpnGateways.

I try this:
```sh
terraformer import google --resources=externalVpnGateways --connect=true --projects=<MY PROJET HERE> --regions=us-east1
```
But I got this:
```log
2020/11/27 18:52:54 google importing... externalVpnGateways
2020/11/27 18:52:55 Refreshing state... google_compute_external_vpn_gateway.tfer--pags
panic: unknown resource type google_compute_external_vpn_gateway

goroutine 148 [running]:
github.com/hashicorp/terraform/plugin.(*GRPCProvider).getResourceSchema(0xc0001e2000, 0x556edabc126e, 0x23, 0x0, 0x0)
	github.com/hashicorp/terraform@v0.12.29/plugin/grpc_provider.go:92 +0x12b
github.com/hashicorp/terraform/plugin.(*GRPCProvider).ReadResource(0xc0001e2000, 0x556edabc126e, 0x23, 0x556ee0c0fa40, 0xc002208160, 0x556edf7cfb60, 0xc0010ca630, 0x556ee5709df0, 0x0, 0x0, ...)
	github.com/hashicorp/terraform@v0.12.29/plugin/grpc_provider.go:321 +0xa5
github.com/GoogleCloudPlatform/terraformer/terraformutils/providerwrapper.(*ProviderWrapper).Refresh(0xc0013d1b00, 0xc000d9a0a0, 0xc000d9a050, 0x2, 0xc000084fa0, 0x43)
	github.com/GoogleCloudPlatform/terraformer/terraformutils/providerwrapper/provider.go:153 +0x28b
github.com/GoogleCloudPlatform/terraformer/terraformutils.(*Resource).Refresh(0xc001c64300, 0xc0013d1b00)
	github.com/GoogleCloudPlatform/terraformer/terraformutils/resource.go:122 +0x51
github.com/GoogleCloudPlatform/terraformer/terraformutils.RefreshResourceWorker(0xc002095740, 0xc000d65bc0, 0xc0013d1b00)
	github.com/GoogleCloudPlatform/terraformer/terraformutils/utils.go:107 +0xd3
created by github.com/GoogleCloudPlatform/terraformer/terraformutils.RefreshResources
	github.com/GoogleCloudPlatform/terraformer/terraformutils/utils.go:77 +0x108
```

**Comment by JohnWillker** [comment]
Solved
How?
Upgrade Terraform to 13
