### ISSUE TITLE
Failing to acquire configurations from Newrelic

### ISSUE THREAD

**Issue by doniz** [GoogleCloudPlatform/terraformer#788]
Hello,

thanks for the great tool that saved us a lot of time. Mainly we using for GCP, but we have had decide to implement on Newrelic as well, but seems it's failing either with new or old versions. Below is the following example:

```
$ terraformer-newrelic import newrelic --path-output="" --path-pattern=".terraformer/{service}/" --resources=synthetics --verbose

2021-02-10T14:32:58.508+0200 [INFO]  plugin: configuring client automatic mTLS
2021-02-10T14:32:58.562+0200 [DEBUG] plugin: starting plugin: path=/Users/donatas/.terraform.d/plugins/darwin_amd64/terraform-provider-newrelic_v2.17.0 args=[/Users/donatas/.terraform.d/plugins/darwin_amd64/terraform-provider-newrelic_v2.17.0]
2021-02-10T14:32:58.567+0200 [DEBUG] plugin: plugin started: path=/Users/donatas/.terraform.d/plugins/darwin_amd64/terraform-provider-newrelic_v2.17.0 pid=32250
2021-02-10T14:32:58.567+0200 [DEBUG] plugin: waiting for RPC address: path=/Users/donatas/.terraform.d/plugins/darwin_amd64/terraform-provider-newrelic_v2.17.0
2021-02-10T14:32:58.587+0200 [INFO]  plugin.terraform-provider-newrelic_v2.17.0: configuring server automatic mTLS: timestamp=2021-02-10T14:32:58.586+0200
2021-02-10T14:32:58.642+0200 [DEBUG] plugin.terraform-provider-newrelic_v2.17.0: plugin address: address=/var/folders/v7/zjjmhmz149x87tnw2wc9n76c0000gn/T/plugin957490665 network=unix timestamp=2021-02-10T14:32:58.642+0200
2021-02-10T14:32:58.642+0200 [DEBUG] plugin: using plugin: version=5
2021-02-10T14:32:58.756+0200 [TRACE] plugin.stdio: waiting for stdio data
2021-02-10T14:32:58.771+0200 [DEBUG] plugin.terraform-provider-newrelic_v2.17.0: 2021/02/10 14:32:58 [INFO] UserAgent: HashiCorp Terraform/0.12.29 (+https://www.terraform.io) Terraform Plugin SDK/1.16.0 terraform-provider-newrelic/2.17.0
2021-02-10T14:32:58.771+0200 [DEBUG] plugin.terraform-provider-newrelic_v2.17.0: 2021/02/10 14:32:58 [INFO] Initializing newrelic-client-go
2021/02/10 14:32:58 newrelic importing... synthetics
2021/02/10 14:33:25 Refreshing state... newrelic_synthetics_monitor.tfer--XXXXXXXXXXXX
2021/02/10 14:33:25 Refreshing state... newrelic_synthetics_monitor.tfer--XXXXXXXXXXXX
2021/02/10 14:33:25 Refreshing state... newrelic_synthetics_monitor.tfer--XXXXXXXXXXXX
2021/02/10 14:33:25 Refreshing state... newrelic_synthetics_monitor.tfer--XXXXXXXXXXXX
2021/02/10 14:33:25 Refreshing state... newrelic_synthetics_monitor.tfer--XXXXXXXXXXXX
2021/02/10 14:33:25 Refreshing state... newrelic_synthetics_monitor.tfer--XXXXXXXXXXXX
2021/02/10 14:33:25 Refreshing state... newrelic_synthetics_monitor.tfer--XXXXXXXXXXXX
2021/02/10 14:33:25 Refreshing state... newrelic_synthetics_monitor.tfer--XXXXXXXXXXXX
2021/02/10 14:33:25 Refreshing state... newrelic_synthetics_monitor.tfer--XXXXXXXXXXXX
2021/02/10 14:33:25 Refreshing state... newrelic_synthetics_monitor.tfer--XXXXXXXXXXXX
2021/02/10 14:33:25 Refreshing state... newrelic_synthetics_monitor.tfer--XXXXXXXXXXXX
2021/02/10 14:33:25 Refreshing state... newrelic_synthetics_monitor.tfer--XXXXXXXXXXXX
2021/02/10 14:33:25 Refreshing state... newrelic_synthetics_monitor.tfer--XXXXXXXXXXXX
2021/02/10 14:33:25 Refreshing state... newrelic_synthetics_monitor.tfer--XXXXXXXXXXXX
2021/02/10 14:33:25 Refreshing state... newrelic_synthetics_monitor.tfer--XXXXXXXXXXXX
2021-02-10T14:33:26.003+0200 [DEBUG] plugin.terraform-provider-newrelic_v2.17.0: panic: interface conversion: interface {} is nil, not *newrelic.ProviderConfig
2021-02-10T14:33:26.003+0200 [DEBUG] plugin.terraform-provider-newrelic_v2.17.0:
2021-02-10T14:33:26.003+0200 [DEBUG] plugin.terraform-provider-newrelic_v2.17.0: goroutine 71 [running]:
2021-02-10T14:33:26.003+0200 [DEBUG] plugin.terraform-provider-newrelic_v2.17.0: github.com/newrelic/terraform-provider-newrelic/v2/newrelic.resourceNewRelicSyntheticsMonitorRead(0xc00057e620, 0x0, 0x0, 0xc00057e620, 0x0)
2021-02-10T14:33:26.003+0200 [DEBUG] plugin.terraform-provider-newrelic_v2.17.0: 	/home/runner/work/terraform-provider-newrelic/terraform-provider-newrelic/newrelic/resource_newrelic_synthetics_monitor.go:211 +0x30d
2021-02-10T14:33:26.003+0200 [DEBUG] plugin.terraform-provider-newrelic_v2.17.0: github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc00012b3b0, 0xc0004420a0, 0x0, 0x0, 0xc00044a5a0, 0xc0004420a0, 0x0)
2021-02-10T14:33:26.003+0200 [DEBUG] plugin.terraform-provider-newrelic_v2.17.0: 	/home/runner/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk@v1.16.0/helper/schema/resource.go:460 +0x119
2021-02-10T14:33:26.003+0200 [DEBUG] plugin.terraform-provider-newrelic_v2.17.0: github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin.(*GRPCProviderServer).ReadResource(0xc000302b30, 0x221da60, 0xc000666030, 0xc0001a6060, 0xc000302b30, 0xc000666030, 0xc0005c9ba0)
2021-02-10T14:33:26.003+0200 [DEBUG] plugin.terraform-provider-newrelic_v2.17.0: 	/home/runner/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk@v1.16.0/internal/helper/plugin/grpc_provider.go:525 +0x3d8
2021-02-10T14:33:26.004+0200 [DEBUG] plugin.terraform-provider-newrelic_v2.17.0: github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5._Provider_ReadResource_Handler(0x1ef1ac0, 0xc000302b30, 0x221da60, 0xc000666030, 0xc0001a6000, 0x0, 0x221da60, 0xc000666030, 0xc000180000, 0xda)
2021-02-10T14:33:26.004+0200 [DEBUG] plugin.terraform-provider-newrelic_v2.17.0: 	/home/runner/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk@v1.16.0/internal/tfplugin5/tfplugin5.pb.go:3269 +0x217
2021-02-10T14:33:26.004+0200 [DEBUG] plugin.terraform-provider-newrelic_v2.17.0: google.golang.org/grpc.(*Server).processUnaryRPC(0xc0003c1500, 0x222b940, 0xc000682600, 0xc000284c00, 0xc000134450, 0x2b3a0f0, 0x0, 0x0, 0x0)
2021-02-10T14:33:26.004+0200 [DEBUG] plugin.terraform-provider-newrelic_v2.17.0: 	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.30.0/server.go:1171 +0x50a
2021-02-10T14:33:26.004+0200 [DEBUG] plugin.terraform-provider-newrelic_v2.17.0: google.golang.org/grpc.(*Server).handleStream(0xc0003c1500, 0x222b940, 0xc000682600, 0xc000284c00, 0x0)
2021-02-10T14:33:26.004+0200 [DEBUG] plugin.terraform-provider-newrelic_v2.17.0: 	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.30.0/server.go:1494 +0xccd
2021-02-10T14:33:26.004+0200 [DEBUG] plugin.terraform-provider-newrelic_v2.17.0: google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc00030c180, 0xc0003c1500, 0x222b940, 0xc000682600, 0xc000284c00)
2021-02-10T14:33:26.004+0200 [DEBUG] plugin.terraform-provider-newrelic_v2.17.0: 	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.30.0/server.go:834 +0xa1
2021-02-10T14:33:26.004+0200 [DEBUG] plugin.terraform-provider-newrelic_v2.17.0: created by google.golang.org/grpc.(*Server).serveStreams.func1
2021-02-10T14:33:26.004+0200 [DEBUG] plugin.terraform-provider-newrelic_v2.17.0: 	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.30.0/server.go:832 +0x204
2021-02-10T14:33:26.009+0200 [DEBUG] plugin: plugin process exited: path=/Users/donatas/.terraform.d/plugins/darwin_amd64/terraform-provider-newrelic_v2.17.0 pid=32250 error="exit status 2"
2021/02/10 14:33:26 WARN: Fail read resource from provider, wait 300ms before retry
2021/02/10 14:33:26 WARN: Fail read resource from provider, wait 300ms before retry
2021/02/10 14:33:26 WARN: Fail read resource from provider, wait 300ms before retry
2021/02/10 14:33:26 WARN: Fail read resource from provider, wait 300ms before retry
2021/02/10 14:33:26 WARN: Fail read resource from provider, wait 300ms before retry
2021/02/10 14:33:26 WARN: Fail read resource from provider, wait 300ms before retry
2021/02/10 14:33:26 WARN: Fail read resource from provider, wait 300ms before retry
2021/02/10 14:33:26 WARN: Fail read resource from provider, wait 300ms before retry
2021/02/10 14:33:26 WARN: Fail read resource from provider, wait 300ms before retry
2021/02/10 14:33:26 WARN: Fail read resource from provider, wait 300ms before retry
2021/02/10 14:33:26 WARN: Fail read resource from provider, wait 300ms before retry
2021/02/10 14:33:26 WARN: Fail read resource from provider, wait 300ms before retry
2021/02/10 14:33:26 WARN: Fail read resource from provider, wait 300ms before retry
2021/02/10 14:33:26 WARN: Fail read resource from provider, wait 300ms before retry
2021/02/10 14:33:26 WARN: Fail read resource from provider, wait 300ms before retry
2021-02-10T14:33:26.011+0200 [WARN]  plugin.stdio: received EOF, stopping recv loop: err="rpc error: code = Unavailable desc = transport is closing"
...
...
...
```

And it's failing with all the resources we tried. 

```
➜  ~ terraformer-newrelic -v && ls -la ~/.terraform.d/plugins/darwin_amd64
version v0.8.10
total 200616
drwxr-xr-x  6 donatas  staff       192 Feb 10 09:34 .
drwxr-xr-x  4 donatas  staff       128 Feb  9 21:23 ..
drwxr-xr-x  3 donatas  staff        96 Jan 23 22:40 archive
drwxr-xr-x  4 donatas  staff       128 Jan 23 22:43 google
-rwxr-xr-x@ 1 donatas  staff  71154880 Jan 23 22:43 terraform-provider-google_v3.53.0_x5
-rwxr-xr-x@ 1 donatas  staff  31559600 Feb  2 20:43 terraform-provider-newrelic_v2.17.0
```

Let me know if I can help with providing more details. 

Thanks in advance.

**Comment by gangsta** [comment]
+ 1

**Comment by doniz** [comment]
Update:

In the beginning I've used compiled version of terraformer. And then I've tried to install from source and it's errored with:

```
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools),
missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
```

So I found that I need to install xcode:

```
xcode-select --install
```

It's started working afterwards. Even I'm using compiled version. 

Note: I used Apple M1 macbook pro on arm.
