### ISSUE TITLE
GitHub Provider - panic: interface conversion: interface {} is nil, not string

### ISSUE THREAD

**Issue by jplanza-gr** [GoogleCloudPlatform/terraformer#902]
@sergeylanzman I'm not sure whether this is a direct result of #894 , but I noticed that you changed "members.go:45" just a few days ago.  I'm trying to import from an SSO-enabled org and I've tried this using two different Personal Access Tokens; one for a bot account that's a member of the org and a second on a personal account that has authorized the token via SSO.  Both tokens have the "admin:org" scope, so they should be able to view these resources.

Please let me know if you need any additional information to troubleshoot this issue.

```
$ terraformer import github --owner=xxxxxx --resources=members --path-output xxxxxx
2021/04/30 12:40:35 github importing organization xxxxxx
2021/04/30 12:40:35 github importing... members
panic: interface conversion: interface {} is nil, not string

goroutine 1 [running]:
github.com/GoogleCloudPlatform/terraformer/providers/github.(*MembersGenerator).InitResources(0xc0016941e0, 0xaa25558, 0xc0016941e0)
	github.com/GoogleCloudPlatform/terraformer/providers/github/members.go:45 +0x637
github.com/GoogleCloudPlatform/terraformer/cmd.initServiceResources(0xc00027dd88, 0x7, 0xaa10530, 0xc0013a9ec0, 0xc000a9c2e0, 0x1, 0x1, 0xe894af0, 0x0, 0x0, ...)
	github.com/GoogleCloudPlatform/terraformer/cmd/import.go:203 +0x302
github.com/GoogleCloudPlatform/terraformer/cmd.initAllServicesResources(0xc0013a58d0, 0xc000a9c2e0, 0x1, 0x1, 0xe894af0, 0x0, 0x0, 0xc000d00630, 0x28, 0x7ffeefbff81e, ...)
	github.com/GoogleCloudPlatform/terraformer/cmd/import.go:160 +0x1e8
github.com/GoogleCloudPlatform/terraformer/cmd.Import(0xaa10530, 0xc000d7ab40, 0xc000a9c2e0, 0x1, 0x1, 0xe894af0, 0x0, 0x0, 0xc000d00630, 0x28, ...)
	github.com/GoogleCloudPlatform/terraformer/cmd/import.go:92 +0x2b8
github.com/GoogleCloudPlatform/terraformer/cmd.newCmdGithubImporter.func1(0xc00027b340, 0xc000a33600, 0x0, 0x4, 0x0, 0x0)
	github.com/GoogleCloudPlatform/terraformer/cmd/provider_cmd_github.go:40 +0x3b8
github.com/spf13/cobra.(*Command).execute(0xc00027b340, 0xc000a335c0, 0x4, 0x4, 0xc00027b340, 0xc000a335c0)
	github.com/spf13/cobra@v1.1.1/command.go:850 +0x472
github.com/spf13/cobra.(*Command).ExecuteC(0xc0017acdc0, 0xc0017eaa20, 0xc00012c050, 0x9e274f8)
	github.com/spf13/cobra@v1.1.1/command.go:958 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.1.1/command.go:895
github.com/GoogleCloudPlatform/terraformer/cmd.Execute(0xa81f420, 0xc0017eaa20)
	github.com/GoogleCloudPlatform/terraformer/cmd/root.go:36 +0x2a
main.main()
	github.com/GoogleCloudPlatform/terraformer/main.go:39 +0x65
```

**Comment by manasrivastava** [comment]
I am getting the same error. Any resolution to this issue?

**Comment by sergeylanzman** [comment]
I try same command on master and I got other error.
Anyway I fixed some bugs with github, tested on githu api.
https://github.com/GoogleCloudPlatform/terraformer/pull/912

**Comment by jplanza-gr** [comment]
This has resolved the issue I was having; thanks!
