### ISSUE TITLE
AWS provider can't handle stopped instances

### ISSUE THREAD

**Issue by sashasimkin** [GoogleCloudPlatform/terraformer#928]
First of all - thanks for the work and effort in putting this tool out! Saves me a lot of time!

Terraformer version: 0.8.13

Failure stack trace:
```
2021/05/11 22:14:12 Refreshing state... aws_instance.tfer--i-002D-0a733c0a81ff73f94_redacted-0020-website
2021/05/11 22:14:12 Refreshing state... aws_instance.tfer--i-002D-0d87956e6dd743a70_redacted
2021/05/11 22:14:12 Refreshing state... aws_instance.tfer--i-002D-0656b75dd4694cb1b_redacted
2021/05/11 22:14:12 Refreshing state... aws_instance.tfer--i-002D-0b2f88b5e7fad6cf5_redacted
panic: interface conversion: interface {} is nil, not []interface {}

goroutine 1 [running]:
github.com/GoogleCloudPlatform/terraformer/providers/aws.(*Ec2Generator).PostConvertHook(0xc001a19980, 0x539b2d4, 0xc001a19980)
        /mnt/c/Users/Alex/Projects/terraformer/providers/aws/ec2.go:99 +0x371
github.com/GoogleCloudPlatform/terraformer/providers/aws.(*AwsFacade).PostConvertHook(0xc00044e460, 0x6896168, 0xc00044e460)
        /mnt/c/Users/Alex/Projects/terraformer/providers/aws/aws_facade.go:75 +0x34
github.com/GoogleCloudPlatform/terraformer/terraformutils.(*ProvidersMapping).CleanupProviders(0xc000ce3530)
        /mnt/c/Users/Alex/Projects/terraformer/terraformutils/providers_mapping.go:175 +0xee
github.com/GoogleCloudPlatform/terraformer/cmd.Import(0x6893948, 0xc000454af0, 0xc000285050, 0x1, 0x1, 0x815c698, 0x0, 0x0, 0x5edad28, 0x1e, ...)
        /mnt/c/Users/Alex/Projects/terraformer/cmd/import.go:104 +0x370
github.com/GoogleCloudPlatform/terraformer/cmd.importRegionResources(0xc000284fb0, 0x1, 0x1, 0x815c698, 0x0, 0x0, 0x5edad28, 0x1e, 0x5e7f80c, 0x9, ...)
        /mnt/c/Users/Alex/Projects/terraformer/cmd/provider_cmd_aws.go:112 +0x225
github.com/GoogleCloudPlatform/terraformer/cmd.newCmdAwsImporter.func1(0xc0001fa840, 0xc0006be2d0, 0x0, 0x3, 0x0, 0x0)
        /mnt/c/Users/Alex/Projects/terraformer/cmd/provider_cmd_aws.go:51 +0x32f
github.com/spf13/cobra.(*Command).execute(0xc0001fa840, 0xc0006be2a0, 0x3, 0x3, 0xc0001fa840, 0xc0006be2a0)
        /home/user/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:850 +0x472
github.com/spf13/cobra.(*Command).ExecuteC(0xc0001fa000, 0xc000284700, 0xc000142000, 0x5f5e2f8)
        /home/user/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:958 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
        /home/user/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:895
github.com/GoogleCloudPlatform/terraformer/cmd.Execute(0x672bfc0, 0xc000284700)
        /mnt/c/Users/Alex/Projects/terraformer/cmd/root.go:36 +0x2a
main.main()
        /mnt/c/Users/Alex/Projects/terraformer/main.go:39 +0x65
```

I went to debug it, and found out that the failure happens in the following place and dataset:
```
> github.com/GoogleCloudPlatform/terraformer/providers/aws.(*Ec2Generator).PostConvertHook() ./providers/aws/ec2.go:98 (hits goroutine(1):6 total:6) (PC: 0x53b0d51)
Warning: debugging optimized function
        rootDeviceVolumeType: ""
    93:         for _, r := range g.Resources {
    94:                 if r.InstanceInfo.Type != "aws_instance" {
    95:                         continue
    96:                 }
    97:                 rootDeviceVolumeType := r.InstanceState.Attributes["root_block_device.0.volume_type"]
=>  98:                 if !(rootDeviceVolumeType == "io1" || rootDeviceVolumeType == "io2" || rootDeviceVolumeType == "gp3") {
    99:                         delete(r.Item["root_block_device"].([]interface{})[0].(map[string]interface{}), "iops")
   100:                 }
   101:                 if rootDeviceVolumeType != "gp3" {
   102:                         delete(r.Item["root_block_device"].([]interface{})[0].(map[string]interface{}), "throughput")
   103:                 }
(dlv) p r.Item["root_block_device"]
Command failed: key not found
(dlv) p r.Item
map[string]interface {} [
        "tags": map[string]interface {} [
                "Name": *(*interface {})(0xc000b5b2a8),
        ],
        "hibernation": "false",
        "credit_specification": []interface {} len: 1, cap: 1, [
                *(*interface {})(0xc0008a4240),
        ],
        "secondary_private_ips": []interface {} len: 1, cap: 1, [
                *(*interface {})(0xc0008a42f0),
        ],
        "cpu_threads_per_core": "1",
        "ipv6_address_count": "0",
        "subnet_id": "subnet-REDACTED",
        "ebs_optimized": "false",
        "source_dest_check": "true",
        "enclave_options": []interface {} len: 1, cap: 1, [
                *(*interface {})(0xc0008a4310),
        ],
        "ami": "ami-REDACTED",
        "disable_api_termination": "true",
        "monitoring": "false",
        "get_password_data": "false",
        "associate_public_ip_address": "true",
        "instance_type": "t2.large",
        "tenancy": "default",
        "vpc_security_group_ids": []interface {} len: 1, cap: 1, [
                *(*interface {})(0xc0008a4180),
        ],
        "key_name": "REDACTED",
        "metadata_options": []interface {} len: 1, cap: 1, [
                *(*interface {})(0xc0008a41e0),
        ],
        "cpu_core_count": "2",
        "private_ip": "REDACTED",
        "tags_all": map[string]interface {} [
                "Name": *(*interface {})(0xc000b5b708),
        ],
        "instance_initiated_shutdown_behavior": "stop",
        "availability_zone": "eu-west-1a",
]
```

I was confused at first, but then went to check the instance in AWS console and noticed it's in stopped state.
It seems like AWS API won't return root device info for stopped instances, so I came up with the following fix, after which the import worked:
```
diff --git a/providers/aws/ec2.go b/providers/aws/ec2.go
index 112c7de6..60b6c92c 100644
--- a/providers/aws/ec2.go
+++ b/providers/aws/ec2.go
@@ -94,13 +94,20 @@ func (g *Ec2Generator) PostConvertHook() error {
                if r.InstanceInfo.Type != "aws_instance" {
                        continue
                }
-               rootDeviceVolumeType := r.InstanceState.Attributes["root_block_device.0.volume_type"]
-               if !(rootDeviceVolumeType == "io1" || rootDeviceVolumeType == "io2" || rootDeviceVolumeType == "gp3") {
-                       delete(r.Item["root_block_device"].([]interface{})[0].(map[string]interface{}), "iops")
-               }
-               if rootDeviceVolumeType != "gp3" {
-                       delete(r.Item["root_block_device"].([]interface{})[0].(map[string]interface{}), "throughput")
+               if block_device, has_block_device_info := r.Item["root_block_device"]; has_block_device_info {
+                       if !has_block_device_info {
+                               continue
+                       }
+
+                       rootDeviceVolumeType := r.InstanceState.Attributes["root_block_device.0.volume_type"]
+                       if !(rootDeviceVolumeType == "io1" || rootDeviceVolumeType == "io2" || rootDeviceVolumeType == "gp3") {
+                               delete(block_device.([]interface{})[0].(map[string]interface{}), "iops")
+                       }
+                       if rootDeviceVolumeType != "gp3" {
+                               delete(block_device.([]interface{})[0].(map[string]interface{}), "throughput")
+                       }
                }
+
        }

        return nil
```

Let me know if you think the fix is okay and doing a pull request makes sense.

**Comment by sashasimkin** [comment]
This is still active.
